db.mexico.insert({ "id": "ed60", "nombre": "15 a 20" })
db.mexico.insert({ "id": "9vrn", "nombre": "24 Horas - El diario sin límites " })
db.mexico.insert({ "id": "ed52", "nombre": "4 Ruedas" })
db.mexico.insert({ "id": "eb82", "nombre": "AD (México)" })
db.mexico.insert({ "id": "ebdp", "nombre": "AD Gourmet" })
db.mexico.insert({ "id": "ee22", "nombre": "Al Día La Piedad" })
db.mexico.insert({ "id": "e751", "nombre": "Al chile" })
db.mexico.insert({ "id": "ea58", "nombre": "Ambiance" })
db.mexico.insert({ "id": "eab4", "nombre": "AmericaEconomia Mexico" })
db.mexico.insert({ "id": "2172", "nombre": "Apertura 2013" })
db.mexico.insert({ "id": "s787", "nombre": "Barcelona" })
db.mexico.insert({ "id": "34lw", "nombre": "Basta" })
db.mexico.insert({ "id": "ec34", "nombre": "Bizz" })
db.mexico.insert({ "id": "ef18", "nombre": "Bloomberg BusinessWeek Mexico" })
db.mexico.insert({ "id": "9vym", "nombre": "CEO Magazine Latam" })
db.mexico.insert({ "id": "9vyn", "nombre": "CEO Magazine North America" })
db.mexico.insert({ "id": "34lu", "nombre": "Campeche Hoy" })
db.mexico.insert({ "id": "t494", "nombre": "Campeon" })
db.mexico.insert({ "id": "9vua", "nombre": "Capital Coahuila" })
db.mexico.insert({ "id": "9vu9", "nombre": "Capital Estado de México" })
db.mexico.insert({ "id": "9vub", "nombre": "Capital Michoacán" })
db.mexico.insert({ "id": "9vu7", "nombre": "Capital México" })
db.mexico.insert({ "id": "9vu8", "nombre": "Capital Querétaro" })
db.mexico.insert({ "id": "ed50", "nombre": "Chic Brides Puebla" })
db.mexico.insert({ "id": "ec37", "nombre": "Chic Lifestyle Nacional" })
db.mexico.insert({ "id": "ec32", "nombre": "Chic Magazine Edo de México" })
db.mexico.insert({ "id": "ec45", "nombre": "Chic Magazine Hidalgo" })
db.mexico.insert({ "id": "ec42", "nombre": "Chic Magazine Jalisco" })
db.mexico.insert({ "id": "ec43", "nombre": "Chic Magazine Laguna" })
db.mexico.insert({ "id": "ec33", "nombre": "Chic Magazine Monterrey" })
db.mexico.insert({ "id": "ec46", "nombre": "Chic Magazine Puebla" })
db.mexico.insert({ "id": "ec44", "nombre": "Chic Magazine Tamaulipas" })
db.mexico.insert({ "id": "ec93", "nombre": "Chic Passport Laguna" })
db.mexico.insert({ "id": "ed21", "nombre": "Chic Passport Monterrey" })
db.mexico.insert({ "id": "ec31", "nombre": "Chic Passport Nacional" })
db.mexico.insert({ "id": "e897", "nombre": "Chilango" })
db.mexico.insert({ "id": "9525", "nombre": "China Daily (Latin America Weekly)" })
db.mexico.insert({ "id": "5808", "nombre": "China Today (Spanish)" })
db.mexico.insert({ "id": "eacr", "nombre": "ContraRéplica" })
db.mexico.insert({ "id": "34n3", "nombre": "Conexiones" })
db.mexico.insert({ "id": "34n1", "nombre": "Correo" })
db.mexico.insert({ "id": "34n2", "nombre": "Ocio Dominical" })
db.mexico.insert({ "id": "eb28", "nombre": "DI:EC" })
db.mexico.insert({ "id": "eb27", "nombre": "DI:ME" })
db.mexico.insert({ "id": "34td", "nombre": "Diario La Verdad (Quintana Roo)" })
db.mexico.insert({ "id": "34te", "nombre": "Diario La Verdad (Yucatán)" })
db.mexico.insert({ "id": "34p8", "nombre": "Diario de Queretaro" })
db.mexico.insert({ "id": "34qf", "nombre": "Diario de Xalapa" })
db.mexico.insert({ "id": "e747", "nombre": "Diario de Yucatán" })
db.mexico.insert({ "id": "e931", "nombre": "Plan B" })
db.mexico.insert({ "id": "e965", "nombre": "Salud" })
db.mexico.insert({ "id": "e962", "nombre": "Sociales" })
db.mexico.insert({ "id": "e969", "nombre": "Suplemento Especial" })
db.mexico.insert({ "id": "34pr", "nombre": "Diario del Sur" })
db.mexico.insert({ "id": "e746", "nombre": "Dime Abuelita por qué" })
db.mexico.insert({ "id": "e898", "nombre": "ELLE (México)" })
db.mexico.insert({ "id": "eabb", "nombre": "El Debate de Culiacán" })
db.mexico.insert({ "id": "eabe", "nombre": "El Debate de Guamuchil" })
db.mexico.insert({ "id": "eabf", "nombre": "El Debate de Guasave" })
db.mexico.insert({ "id": "eabd", "nombre": "El Debate de Los Mochis" })
db.mexico.insert({ "id": "eabc", "nombre": "El Debate de Mazatlan" })
db.mexico.insert({ "id": "9knx", "nombre": "El Diario de Chihuahua " })
db.mexico.insert({ "id": "9kp1", "nombre": "El Diario de Delicias" })
db.mexico.insert({ "id": "e803", "nombre": "El Diario de Juárez" })
db.mexico.insert({ "id": "9kn9", "nombre": "Espacios" })
db.mexico.insert({ "id": "e878", "nombre": "Especiales (Diario de Juárez)" })
db.mexico.insert({ "id": "e805", "nombre": "El Diario de Nuevo Casas Grandes" })
db.mexico.insert({ "id": "e858", "nombre": "Autos" })
db.mexico.insert({ "id": "ef22", "nombre": "DxT" })
db.mexico.insert({ "id": "2034", "nombre": "El Economista (México)" })
db.mexico.insert({ "id": "e948", "nombre": "Estrategias" })
db.mexico.insert({ "id": "e879", "nombre": "Fondos" })
db.mexico.insert({ "id": "ebbu", "nombre": "Industria Automotriz" })
db.mexico.insert({ "id": "e861", "nombre": "Los Políticos" })
db.mexico.insert({ "id": "e867", "nombre": "Previsión" })
db.mexico.insert({ "id": "ed33", "nombre": "Reporte Especial" })
db.mexico.insert({ "id": "e857", "nombre": "Termómetro Económico" })
db.mexico.insert({ "id": "e863", "nombre": "The Washington Post  (Mexico)" })
db.mexico.insert({ "id": "e860", "nombre": "Turismo" })
db.mexico.insert({ "id": "e865", "nombre": "Uniones" })
db.mexico.insert({ "id": "2132", "nombre": "El Financiero (Mexico)" })
db.mexico.insert({ "id": "ef16", "nombre": "El Financiero Bajío" })
db.mexico.insert({ "id": "ef17", "nombre": "El Financiero Monterrey" })
db.mexico.insert({ "id": "e959", "nombre": "El Guardián" })
db.mexico.insert({ "id": "34ps", "nombre": "El Heraldo de Chiapas" })
db.mexico.insert({ "id": "34pu", "nombre": "El Heraldo de Chihuahua" })
db.mexico.insert({ "id": "34pt", "nombre": "El Heraldo de Tabasco" })
db.mexico.insert({ "id": "eabt", "nombre": "El Financiero" })
db.mexico.insert({ "id": "eabn", "nombre": "El Informador" })
db.mexico.insert({ "id": "eabp", "nombre": "Gente Bien" })
db.mexico.insert({ "id": "eabr", "nombre": "Suplemento 1" })
db.mexico.insert({ "id": "ec25", "nombre": "El Mundo" })
db.mexico.insert({ "id": "ed14", "nombre": "El Mundo de Córdoba" })
db.mexico.insert({ "id": "ed16", "nombre": "El Mundo de Orizaba" })
db.mexico.insert({ "id": "ed15", "nombre": "El Mundo de Tecamachalco" })
db.mexico.insert({ "id": "ed17", "nombre": "El Mundo de Tehuacán" })
db.mexico.insert({ "id": "34ku", "nombre": "El Norte" })
db.mexico.insert({ "id": "34qj", "nombre": "El Occidental" })
db.mexico.insert({ "id": "34qk", "nombre": "El Sol de Acapulco" })
db.mexico.insert({ "id": "34nr", "nombre": "El Sol de Cuautla" })
db.mexico.insert({ "id": "34nq", "nombre": "El Sol de Cuernavaca" })
db.mexico.insert({ "id": "34qm", "nombre": "El Sol de Durango" })
db.mexico.insert({ "id": "34np", "nombre": "El Sol de Hermosillo" })
db.mexico.insert({ "id": "34qn", "nombre": "El Sol de Hidalgo" })
db.mexico.insert({ "id": "34pb", "nombre": "El Sol de Irapuato" })
db.mexico.insert({ "id": "34pd", "nombre": "El Sol de León" })
db.mexico.insert({ "id": "34pw", "nombre": "El Sol de Mazatlan" })
db.mexico.insert({ "id": "34py", "nombre": "El Sol de Morelia" })
db.mexico.insert({ "id": "34ns", "nombre": "El Sol de México" })
db.mexico.insert({ "id": "34pv", "nombre": "El Sol de Parral" })
db.mexico.insert({ "id": "34pe", "nombre": "El Sol de Puebla" })
db.mexico.insert({ "id": "34pc", "nombre": "El Sol de Salamanca" })
db.mexico.insert({ "id": "34p9", "nombre": "El Sol de San Juan del Río" })
db.mexico.insert({ "id": "34pf", "nombre": "El Sol de San Luis Potosí" })
db.mexico.insert({ "id": "34px", "nombre": "El Sol de Sinaloa" })
db.mexico.insert({ "id": "34pg", "nombre": "El Sol de Tampico" })
db.mexico.insert({ "id": "34nv", "nombre": "El Sol de Tijuana" })
db.mexico.insert({ "id": "34pz", "nombre": "El Sol de Tlaxcala" })
db.mexico.insert({ "id": "34ph", "nombre": "El Sol de Toluca" })
db.mexico.insert({ "id": "34qp", "nombre": "El Sol de Tulancingo" })
db.mexico.insert({ "id": "34qs", "nombre": "El Sol de Zacatecas" })
db.mexico.insert({ "id": "34qr", "nombre": "El Sol de Zamora" })
db.mexico.insert({ "id": "34pa", "nombre": "El Sol del Bajío" })
db.mexico.insert({ "id": "34ql", "nombre": "El Sol del Centro" })
db.mexico.insert({ "id": "34q1", "nombre": "El Sudcaliforniano" })
db.mexico.insert({ "id": "eabq", "nombre": "El Tren" })
db.mexico.insert({ "id": "2053", "nombre": "El Universal" })
db.mexico.insert({ "id": "9khg", "nombre": "Empleos (Paso del Norte)" })
db.mexico.insert({ "id": "e880", "nombre": "Equestrian Life Style" })
db.mexico.insert({ "id": "34nx", "nombre": "Esto" })
db.mexico.insert({ "id": "s864", "nombre": "Eurocopa 2012" })
db.mexico.insert({ "id": "e908", "nombre": "Excelsior (México)" })
db.mexico.insert({ "id": "e894", "nombre": "Expansion (México)" })
db.mexico.insert({ "id": "e652", "nombre": "Food and Travel (México)" })
db.mexico.insert({ "id": "eb68", "nombre": "GQ (México)" })
db.mexico.insert({ "id": "ebdn", "nombre": "GQ Motors" })
db.mexico.insert({ "id": "ebdm", "nombre": "GQ Style (Mexico)" })
db.mexico.insert({ "id": "ed70", "nombre": "H para Hombres" })
db.mexico.insert({ "id": "ea90", "nombre": "Horloger" })
db.mexico.insert({ "id": "34mf", "nombre": "Hotbook Magazine" })
db.mexico.insert({ "id": "34mg", "nombre": "Hotbook News" })
db.mexico.insert({ "id": "e893", "nombre": "InStyle (México)" })
db.mexico.insert({ "id": "eabg", "nombre": "La I de Culiacan" })
db.mexico.insert({ "id": "eabh", "nombre": "La I de Los Mochis" })
db.mexico.insert({ "id": "eabj", "nombre": "La I de Mazatlán" })
db.mexico.insert({ "id": "2033", "nombre": "La Jornada" })
db.mexico.insert({ "id": "34nw", "nombre": "La Voz de la Frontera" })
db.mexico.insert({ "id": "e749", "nombre": "La i Campeche" })
db.mexico.insert({ "id": "e748", "nombre": "La i Merida" })
db.mexico.insert({ "id": "e895", "nombre": "Life and Style (México)" })
db.mexico.insert({ "id": "e896", "nombre": "Manufactura" })
db.mexico.insert({ "id": "ebbz", "nombre": "Manufactura (Paso del Norte)" })
db.mexico.insert({ "id": "t475", "nombre": "Messi" })
db.mexico.insert({ "id": "s987", "nombre": "Mexico Champion 2012" })
db.mexico.insert({ "id": "e707", "nombre": "Mi Súper Diario" })
db.mexico.insert({ "id": "ec29", "nombre": "Campus" })
db.mexico.insert({ "id": "ec28", "nombre": "Laberinto" })
db.mexico.insert({ "id": "ec26", "nombre": "Mercados Milenio" })
db.mexico.insert({ "id": "2073", "nombre": "Milenio" })
db.mexico.insert({ "id": "ec30", "nombre": "Todas" })
db.mexico.insert({ "id": "ec17", "nombre": "Milenio Edo de México" })
db.mexico.insert({ "id": "ec23", "nombre": "Milenio Hidalgo" })
db.mexico.insert({ "id": "ec19", "nombre": "Milenio Jalisco" })
db.mexico.insert({ "id": "ec20", "nombre": "Milenio Laguna" })
db.mexico.insert({ "id": "ec22", "nombre": "Milenio León" })
db.mexico.insert({ "id": "ec18", "nombre": "Milenio Monterrey" })
db.mexico.insert({ "id": "ec47", "nombre": "Entre Aulas" })
db.mexico.insert({ "id": "ec24", "nombre": "Milenio Puebla" })
db.mexico.insert({ "id": "ec21", "nombre": "Milenio Tamaulipas" })
db.mexico.insert({ "id": "34kv", "nombre": "Mural" })
db.mexico.insert({ "id": "e195", "nombre": "Más por más" })
db.mexico.insert({ "id": "s988", "nombre": "NFL 2017" })
db.mexico.insert({ "id": "t597", "nombre": "NFL Temporada 2013" })
db.mexico.insert({ "id": "eb24", "nombre": "Newsweek en Español" })
db.mexico.insert({ "id": "ee60", "nombre": "Notas para ti" })
db.mexico.insert({ "id": "34qq", "nombre": "Noticias del Sol de la Laguna" })
db.mexico.insert({ "id": "ed59", "nombre": "Nueva (Mexico)" })
db.mexico.insert({ "id": "e862", "nombre": "O'clock" })
db.mexico.insert({ "id": "e899", "nombre": "Obras" })
db.mexico.insert({ "id": "eabk", "nombre": "Perfiles Culiacán" })
db.mexico.insert({ "id": "eabm", "nombre": "Perfiles Mazatlán" })
db.mexico.insert({ "id": "eabl", "nombre": "Perfiles de los Mochis" })
db.mexico.insert({ "id": "e939", "nombre": "Periodico Al Día (Léon)" })
db.mexico.insert({ "id": "e933", "nombre": "Periódico AM (León)" })
db.mexico.insert({ "id": "e937", "nombre": "Periódico AM Express (Guanajuato)" })
db.mexico.insert({ "id": "e938", "nombre": "Periódico AM Express (San Francisco del Ricón)" })
db.mexico.insert({ "id": "e935", "nombre": "Periódico AM Express Celaya" })
db.mexico.insert({ "id": "e934", "nombre": "Periódico AM Express Irapuato" })
db.mexico.insert({ "id": "e970", "nombre": "Periódico AM Express Norte" })
db.mexico.insert({ "id": "e941", "nombre": "Periódico Al Día (Celaya)" })
db.mexico.insert({ "id": "e940", "nombre": "Periódico Al Día (Irapuato)" })
db.mexico.insert({ "id": "e944", "nombre": "Periódico Al Día (Moroléon)" })
db.mexico.insert({ "id": "e943", "nombre": "Periódico Al Día (Salamanca)" })
db.mexico.insert({ "id": "ed35", "nombre": "Publimetro Ciudad de México" })
db.mexico.insert({ "id": "ed36", "nombre": "Publimetro Guadalajara" })
db.mexico.insert({ "id": "ed37", "nombre": "Publimetro Monterrey" })
db.mexico.insert({ "id": "eb88", "nombre": "Publimetro Mérida" })
db.mexico.insert({ "id": "tb24", "nombre": "Pásala!" })
db.mexico.insert({ "id": "34lv", "nombre": "Quintana Roo Hoy" })
db.mexico.insert({ "id": "e900", "nombre": "Quién" })
db.mexico.insert({ "id": "s788", "nombre": "Real Madrid" })
db.mexico.insert({ "id": "34kt", "nombre": "Reforma" })
db.mexico.insert({ "id": "9vu5", "nombre": "Reporte Índigo Guadalajara" })
db.mexico.insert({ "id": "9vu6", "nombre": "Reporte Índigo Monterrey" })
db.mexico.insert({ "id": "9vu4", "nombre": "Reporte Índigo Nacional" })
db.mexico.insert({ "id": "ea44", "nombre": "Revista +Ciencia de la Facultad de Ingeniería" })
db.mexico.insert({ "id": "eaby", "nombre": "Rolling Stone (Mexico)" })
db.mexico.insert({ "id": "ta93", "nombre": "Record aniversario" })
db.mexico.insert({ "id": "2133", "nombre": "Récord" })
db.mexico.insert({ "id": "ed53", "nombre": "TVNotas" })
db.mexico.insert({ "id": "ed82", "nombre": "TVNotas  Especial Horoscopos" })
db.mexico.insert({ "id": "34lt", "nombre": "Tabasco Hoy" })
db.mexico.insert({ "id": "2149", "nombre": "The Champion Magazine" })
db.mexico.insert({ "id": "2169", "nombre": "Todo Sobre Sudafrica" })
db.mexico.insert({ "id": "34ny", "nombre": "Tribuna de San Luis" })
db.mexico.insert({ "id": "34lx", "nombre": "Unis y Mas" })
db.mexico.insert({ "id": "eb80", "nombre": "VOGUE México" })
db.mexico.insert({ "id": "e808", "nombre": "Vamos (Cd. Juárez)" })
db.mexico.insert({ "id": "e953", "nombre": "Circulo 360" })
db.mexico.insert({ "id": "e954", "nombre": "Domingo 360 " })
db.mexico.insert({ "id": "2102", "nombre": "Vanguardia" })
db.mexico.insert({ "id": "2171", "nombre": "Veintitantos" })
db.mexico.insert({ "id": "9hyc", "nombre": "Viajero" })
db.mexico.insert({ "id": "ebdh", "nombre": "Vogue Belleza" })
db.mexico.insert({ "id": "ebdj", "nombre": "Vogue Hombre" })
db.mexico.insert({ "id": "ebdk", "nombre": "Vogue Novias" })
db.mexico.insert({ "id": "e874", "nombre": "home:tech magazine méxico" })
db.mexico.insert({ "id": "e875", "nombre": "inst:all magazine méxico" })
db.mexico.insert({ "id": "e876", "nombre": "music:life magazine méxico" })
db.mexico.insert({ "id": "e877", "nombre": "sound:check magazine méxico" })
