db.estadosUnidos.insertOne({ "id": "9vrc", "nombre": " Antelope Valley Press (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9a06", "nombre": "3D World" })
db.estadosUnidos.insertOne({ "id": "9vhj", "nombre": "4 Wheel &amp; Off Road" })
db.estadosUnidos.insertOne({ "id": "9htb", "nombre": "ABC Soaps In Depth" })
db.estadosUnidos.insertOne({ "id": "ebds", "nombre": "AD Latinoamerica" })
db.estadosUnidos.insertOne({ "id": "9jd8", "nombre": "Accounting Today" })
db.estadosUnidos.insertOne({ "id": "6625", "nombre": "Aerotech News and Review" })
db.estadosUnidos.insertOne({ "id": "9ghu", "nombre": "Air &amp; Space Smithsonian" })
db.estadosUnidos.insertOne({ "id": "9an6", "nombre": "Airguide Destinations Airport Guide - Atlanta (ATL)" })
db.estadosUnidos.insertOne({ "id": "9an7", "nombre": "Airguide Destinations Airport Guide - Detroit (DTW)" })
db.estadosUnidos.insertOne({ "id": "9ang", "nombre": "Airguide Destinations Airport Guide - Los Angeles (LAX)" })
db.estadosUnidos.insertOne({ "id": "9an9", "nombre": "Airguide Destinations Airport Guide - Miami (MIA)" })
db.estadosUnidos.insertOne({ "id": "9ana", "nombre": "Airguide Destinations Airport Guide - Minneapolis St. Paul (MSP)" })
db.estadosUnidos.insertOne({ "id": "9anb", "nombre": "Airguide Destinations Airport Guide - New York (JFK, LGA, EWR)" })
db.estadosUnidos.insertOne({ "id": "9anh", "nombre": "Airguide Destinations Airport Guide - Salt Lake City (SLC)" })
db.estadosUnidos.insertOne({ "id": "9anj", "nombre": "Airguide Destinations Airport Guide - San Francisco (SFO)" })
db.estadosUnidos.insertOne({ "id": "9and", "nombre": "Airguide Destinations Airport Guide - Seattle (SEA)" })
db.estadosUnidos.insertOne({ "id": "909a", "nombre": "Albany Times Union" })
db.estadosUnidos.insertOne({ "id": "909b", "nombre": "Albany Times Union (Sunday)" })
db.estadosUnidos.insertOne({ "id": "1369", "nombre": "Albuquerque Journal" })
db.estadosUnidos.insertOne({ "id": "v301", "nombre": "Parade" })
db.estadosUnidos.insertOne({ "id": "9k93", "nombre": "All About Italy (USA)" })
db.estadosUnidos.insertOne({ "id": "9wtv", "nombre": "All Region Prep Sports Awards" })
db.estadosUnidos.insertOne({ "id": "9hph", "nombre": "Alternative Medicine" })
db.estadosUnidos.insertOne({ "id": "9e48", "nombre": "Amazing Wellness" })
db.estadosUnidos.insertOne({ "id": "9blh", "nombre": "American Art Collector" })
db.estadosUnidos.insertOne({ "id": "9kgn", "nombre": "American Farmhouse Style" })
db.estadosUnidos.insertOne({ "id": "9blj", "nombre": "American Fine Art Magazine" })
db.estadosUnidos.insertOne({ "id": "9j84", "nombre": "American Survival Guide" })
db.estadosUnidos.insertOne({ "id": "3014", "nombre": "Amerika Woche" })
db.estadosUnidos.insertOne({ "id": "9km5", "nombre": "Anglers Journal" })
db.estadosUnidos.insertOne({ "id": "9ht6", "nombre": "Animal Tales" })
db.estadosUnidos.insertOne({ "id": "9657", "nombre": "Animation Magazine" })
db.estadosUnidos.insertOne({ "id": "sa40", "nombre": "Annie's Christmas" })
db.estadosUnidos.insertOne({ "id": "sama", "nombre": "Annie's Christmas Winter 2018 Special" })
db.estadosUnidos.insertOne({ "id": "sf96", "nombre": "Annie's Coloring Pages " })
db.estadosUnidos.insertOne({ "id": "9jcv", "nombre": "Annie's Crochet in a Weekend" })
db.estadosUnidos.insertOne({ "id": "9vsr", "nombre": "Annie's Fast, Easy, Fun, Crochet Fall 2018" })
db.estadosUnidos.insertOne({ "id": "9blp", "nombre": "Annie's Quilt Spring 2019" })
db.estadosUnidos.insertOne({ "id": "9gp7", "nombre": "Annie's Quilting for the Home" })
db.estadosUnidos.insertOne({ "id": "9gtk", "nombre": "Annie's Quilting with Precuts" })
db.estadosUnidos.insertOne({ "id": "9afe", "nombre": "Annie's Time-friendly Quilts" })
db.estadosUnidos.insertOne({ "id": "9kgt", "nombre": "Annie's Weekend Sewing April 2019" })
db.estadosUnidos.insertOne({ "id": "9kj7", "nombre": "Antelope Valley Press" })
db.estadosUnidos.insertOne({ "id": "9amg", "nombre": "Express (USA)" })
db.estadosUnidos.insertOne({ "id": "9amh", "nombre": "Lifestyle (Antelope Valley)" })
db.estadosUnidos.insertOne({ "id": "9vxx", "nombre": "Apple Magazine" })
db.estadosUnidos.insertOne({ "id": "1074", "nombre": "Arkansas Democrat-Gazette" })
db.estadosUnidos.insertOne({ "id": "ee16", "nombre": "Arte por Excelencias" })
db.estadosUnidos.insertOne({ "id": "9e71", "nombre": "Arts and Crafts Homes" })
db.estadosUnidos.insertOne({ "id": "9hzt", "nombre": "Aspen Peak" })
db.estadosUnidos.insertOne({ "id": "34kh", "nombre": "Athleisure" })
db.estadosUnidos.insertOne({ "id": "9ak9", "nombre": "Atomic Ranch" })
db.estadosUnidos.insertOne({ "id": "9hzu", "nombre": "Austin Way" })
db.estadosUnidos.insertOne({ "id": "9vkp", "nombre": "Automobile" })
db.estadosUnidos.insertOne({ "id": "9f75", "nombre": "BBC Good Food" })
db.estadosUnidos.insertOne({ "id": "9e55", "nombre": "Backpacker" })
db.estadosUnidos.insertOne({ "id": "ef27", "nombre": "Bajo El Sol" })
db.estadosUnidos.insertOne({ "id": "1116", "nombre": "Baltimore Sun" })
db.estadosUnidos.insertOne({ "id": "1209", "nombre": "Baltimore Sun Sunday" })
db.estadosUnidos.insertOne({ "id": "9amc", "nombre": "Belleville News-Democrat" })
db.estadosUnidos.insertOne({ "id": "9vwm", "nombre": "Belleville News-Democrat (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9e49", "nombre": "Better Nutrition" })
db.estadosUnidos.insertOne({ "id": "9if2", "nombre": "Birds &amp; Blooms" })
db.estadosUnidos.insertOne({ "id": "9e70", "nombre": "Black Belt" })
db.estadosUnidos.insertOne({ "id": "9go8", "nombre": "Bloomberg Businessweek (Asia)" })
db.estadosUnidos.insertOne({ "id": "9go9", "nombre": "Bloomberg Businessweek (Europe)" })
db.estadosUnidos.insertOne({ "id": "9gnp", "nombre": "Bloomberg Businessweek (North America)" })
db.estadosUnidos.insertOne({ "id": "9i74", "nombre": "Boating" })
db.estadosUnidos.insertOne({ "id": "9514", "nombre": "Bonita &amp; Estero Magazine" })
db.estadosUnidos.insertOne({ "id": "9hzv", "nombre": "Boston Common" })
db.estadosUnidos.insertOne({ "id": "1089", "nombre": "Boston Herald" })
db.estadosUnidos.insertOne({ "id": "sfdy", "nombre": "Brain Games" })
db.estadosUnidos.insertOne({ "id": "9352", "nombre": "Business Traveler (USA)" })
db.estadosUnidos.insertOne({ "id": "sarm", "nombre": "C.A.R.E." })
db.estadosUnidos.insertOne({ "id": "9kgp", "nombre": "C10 Builder's Guide" })
db.estadosUnidos.insertOne({ "id": "9ht5", "nombre": "CBS Soaps In Depth" })
db.estadosUnidos.insertOne({ "id": "1586", "nombre": "Calhoun Times" })
db.estadosUnidos.insertOne({ "id": "9hrd", "nombre": "Cape Coral Living" })
db.estadosUnidos.insertOne({ "id": "9hzw", "nombre": "Capitol File" })
db.estadosUnidos.insertOne({ "id": "9vkm", "nombre": "Car Craft" })
db.estadosUnidos.insertOne({ "id": "9d82", "nombre": "Catron Courier" })
db.estadosUnidos.insertOne({ "id": "9hnm", "nombre": "Cecil Whig" })
db.estadosUnidos.insertOne({ "id": "9vte", "nombre": "Centre Daily Times" })
db.estadosUnidos.insertOne({ "id": "9ams", "nombre": "Centre Daily Times (Sunday)" })
db.estadosUnidos.insertOne({ "id": "8431", "nombre": "Chattanooga Times Free Press" })
db.estadosUnidos.insertOne({ "id": "9073", "nombre": "ChattanoogaNow" })
db.estadosUnidos.insertOne({ "id": "9072", "nombre": "Parade" })
db.estadosUnidos.insertOne({ "id": "9vko", "nombre": "Chevy High Performance" })
db.estadosUnidos.insertOne({ "id": "1221", "nombre": "Chicago Sun-Times" })
db.estadosUnidos.insertOne({ "id": "9vzn", "nombre": "Chicago Sun-Times (Sunday)" })
db.estadosUnidos.insertOne({ "id": "1055", "nombre": "Chicago Tribune" })
db.estadosUnidos.insertOne({ "id": "9amf", "nombre": "Chicago Tribune (Sunday)" })
db.estadosUnidos.insertOne({ "id": "7652", "nombre": "China Daily (USA)" })
db.estadosUnidos.insertOne({ "id": "5709", "nombre": "China Today (English)" })
db.estadosUnidos.insertOne({ "id": "9595", "nombre": "Classic Ford" })
db.estadosUnidos.insertOne({ "id": "9vkq", "nombre": "Classic Trucks" })
db.estadosUnidos.insertOne({ "id": "9592", "nombre": "Classics Monthly" })
db.estadosUnidos.insertOne({ "id": "9e89", "nombre": "Clean Eating" })
db.estadosUnidos.insertOne({ "id": "9e54", "nombre": "Climbing" })
db.estadosUnidos.insertOne({ "id": "9hsz", "nombre": "Closer Weekly" })
db.estadosUnidos.insertOne({ "id": "9542", "nombre": "Computer Music" })
db.estadosUnidos.insertOne({ "id": "9j85", "nombre": "Concealed Carry Hand Guns" })
db.estadosUnidos.insertOne({ "id": "9fgq", "nombre": "Connecticut Post" })
db.estadosUnidos.insertOne({ "id": "9fgs", "nombre": "Connecticut Post (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9al1", "nombre": "Cottages &amp; Bungalows" })
db.estadosUnidos.insertOne({ "id": "9if8", "nombre": "Country" })
db.estadosUnidos.insertOne({ "id": "9d86", "nombre": "Country Sampler" })
db.estadosUnidos.insertOne({ "id": "9fef", "nombre": "Country Sampler - BOHO Style" })
db.estadosUnidos.insertOne({ "id": "9jf2", "nombre": "Country Sampler - Celebrating Everyday Life" })
db.estadosUnidos.insertOne({ "id": "9kjp", "nombre": "Country Sampler - Christmas Decorating" })
db.estadosUnidos.insertOne({ "id": "9aff", "nombre": "Country Sampler - Farmhouse Style" })
db.estadosUnidos.insertOne({ "id": "9kgw", "nombre": "Country Sampler - Gardens Spring 2019" })
db.estadosUnidos.insertOne({ "id": "9gvp", "nombre": "Country Sampler - Home Tours" })
db.estadosUnidos.insertOne({ "id": "9kgm", "nombre": "Country Sampler - Home Tours April 2019" })
db.estadosUnidos.insertOne({ "id": "9jf3", "nombre": "Country Sampler - Modern Country" })
db.estadosUnidos.insertOne({ "id": "9jf1", "nombre": "Country Sampler - Prairie Style" })
db.estadosUnidos.insertOne({ "id": "9gvw", "nombre": "Country Sampler - Spring Decorating" })
db.estadosUnidos.insertOne({ "id": "sgh0", "nombre": "Country Sampler Autumn Decorating SIP 2018" })
db.estadosUnidos.insertOne({ "id": "9kgg", "nombre": "Country Sampler Holiday Homes December 2018" })
db.estadosUnidos.insertOne({ "id": "9if3", "nombre": "Country Woman" })
db.estadosUnidos.insertOne({ "id": "9gf3", "nombre": "Craft Beer &amp; Brewing Magazine" })
db.estadosUnidos.insertOne({ "id": "9d65", "nombre": "Creative Knitting" })
db.estadosUnidos.insertOne({ "id": "9kgh", "nombre": "Creative Knitting - Graceful Lace SIP 2019" })
db.estadosUnidos.insertOne({ "id": "9gvn", "nombre": "Creative Knitting - Simple Knits for Spring and Summer" })
db.estadosUnidos.insertOne({ "id": "9jd0", "nombre": "Credit Union Journal" })
db.estadosUnidos.insertOne({ "id": "9jf4", "nombre": "Crochet - Boutique Style" })
db.estadosUnidos.insertOne({ "id": "9d68", "nombre": "Crochet World" })
db.estadosUnidos.insertOne({ "id": "9kgj", "nombre": "Crochet World - All-Time Favorite Afghans Spring 2019 SIP" })
db.estadosUnidos.insertOne({ "id": "9gvr", "nombre": "Crochet World - Crochet Gifts for all Occasions" })
db.estadosUnidos.insertOne({ "id": "9d67", "nombre": "Crochet!" })
db.estadosUnidos.insertOne({ "id": "samb", "nombre": "Crochet! October 2018 Special" })
db.estadosUnidos.insertOne({ "id": "9a05", "nombre": "Cross Stitcher" })
db.estadosUnidos.insertOne({ "id": "9i75", "nombre": "Cruising World" })
db.estadosUnidos.insertOne({ "id": "9i76", "nombre": "Cycle World" })
db.estadosUnidos.insertOne({ "id": "9544", "nombre": "Cycling Plus" })
db.estadosUnidos.insertOne({ "id": "4886", "nombre": "DA MAN" })
db.estadosUnidos.insertOne({ "id": "9497", "nombre": "DNA Magazine" })
db.estadosUnidos.insertOne({ "id": "9a86", "nombre": "DREAM TEEN Magazine" })
db.estadosUnidos.insertOne({ "id": "8525", "nombre": "Daily Freeman (Kingston, NY)" })
db.estadosUnidos.insertOne({ "id": "8481", "nombre": "Daily Local News (West Chester, PA)" })
db.estadosUnidos.insertOne({ "id": "9kyq", "nombre": "Daily Press" })
db.estadosUnidos.insertOne({ "id": "9kyw", "nombre": "Daily Press (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9gb6", "nombre": "Daily Racing Form National Digital Edition" })
db.estadosUnidos.insertOne({ "id": "9gb7", "nombre": "Daily Racing Form Saturday Stakes Preview" })
db.estadosUnidos.insertOne({ "id": "9kys", "nombre": "Daily Southtown" })
db.estadosUnidos.insertOne({ "id": "9kgc", "nombre": "Daily Southtown (Sunday)" })
db.estadosUnidos.insertOne({ "id": "8524", "nombre": "Daily Times (Primos, PA)" })
db.estadosUnidos.insertOne({ "id": "7330", "nombre": "Dayton Daily News" })
db.estadosUnidos.insertOne({ "id": "ef29", "nombre": "Desert Flightline" })
db.estadosUnidos.insertOne({ "id": "9a43", "nombre": "DestinAsian" })
db.estadosUnidos.insertOne({ "id": "9ic7", "nombre": "Die Cast X" })
db.estadosUnidos.insertOne({ "id": "9vji", "nombre": "Diesel Power" })
db.estadosUnidos.insertOne({ "id": "9al5", "nombre": "Diesel World" })
db.estadosUnidos.insertOne({ "id": "9486", "nombre": "Digital Camera World" })
db.estadosUnidos.insertOne({ "id": "9jda", "nombre": "Digital Insurance" })
db.estadosUnidos.insertOne({ "id": "9hp5", "nombre": "Dorchester Star" })
db.estadosUnidos.insertOne({ "id": "9al2", "nombre": "Drag Racer" })
db.estadosUnidos.insertOne({ "id": "9e63", "nombre": "Dressage Today" })
db.estadosUnidos.insertOne({ "id": "9627", "nombre": "EDGE" })
db.estadosUnidos.insertOne({ "id": "9e64", "nombre": "EQUUS" })
db.estadosUnidos.insertOne({ "id": "2075", "nombre": "El Diario" })
db.estadosUnidos.insertOne({ "id": "e804", "nombre": "El Diario de El Paso" })
db.estadosUnidos.insertOne({ "id": "9166", "nombre": "El Dorado News-Times" })
db.estadosUnidos.insertOne({ "id": "2023", "nombre": "El Nuevo Herald" })
db.estadosUnidos.insertOne({ "id": "9vwt", "nombre": "El Nuevo Herald (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9jdb", "nombre": "Employee Benefit News" })
db.estadosUnidos.insertOne({ "id": "9kgs", "nombre": "Essentially America" })
db.estadosUnidos.insertOne({ "id": "9kgq", "nombre": "F-100 Builder's Guide" })
db.estadosUnidos.insertOne({ "id": "9if5", "nombre": "Farm &amp; Ranch Living" })
db.estadosUnidos.insertOne({ "id": "9607", "nombre": "Fast Bikes" })
db.estadosUnidos.insertOne({ "id": "9608", "nombre": "Fast Car" })
db.estadosUnidos.insertOne({ "id": "9hrt", "nombre": "Fast Company" })
db.estadosUnidos.insertOne({ "id": "9593", "nombre": "Fast Ford" })
db.estadosUnidos.insertOne({ "id": "9i46", "nombre": "Field and Stream" })
db.estadosUnidos.insertOne({ "id": "9jd4", "nombre": "Financial Planning" })
db.estadosUnidos.insertOne({ "id": "9j86", "nombre": "Firepower" })
db.estadosUnidos.insertOne({ "id": "9ht1", "nombre": "First For Women" })
db.estadosUnidos.insertOne({ "id": "9al3", "nombre": "Flea Market Décor" })
db.estadosUnidos.insertOne({ "id": "9ic8", "nombre": "Flight Journal" })
db.estadosUnidos.insertOne({ "id": "9i78", "nombre": "Flying" })
db.estadosUnidos.insertOne({ "id": "9vhg", "nombre": "Footwear News" })
db.estadosUnidos.insertOne({ "id": "9g84", "nombre": "Forbes" })
db.estadosUnidos.insertOne({ "id": "9hrk", "nombre": "Foreword Reviews" })
db.estadosUnidos.insertOne({ "id": "3091", "nombre": "Forward (Yiddish Edition)" })
db.estadosUnidos.insertOne({ "id": "7062", "nombre": "Forward Magazine" })
db.estadosUnidos.insertOne({ "id": "9vk9", "nombre": "Four Wheeler" })
db.estadosUnidos.insertOne({ "id": "9jaf", "nombre": "Frequent Flyer Destinations" })
db.estadosUnidos.insertOne({ "id": "9229", "nombre": "GA Voice" })
db.estadosUnidos.insertOne({ "id": "eb86", "nombre": "GQ Latinoamerica" })
db.estadosUnidos.insertOne({ "id": "9jab", "nombre": "Gervois" })
db.estadosUnidos.insertOne({ "id": "9jas", "nombre": "Girls' Life" })
db.estadosUnidos.insertOne({ "id": "9ht8", "nombre": "Girls' World" })
db.estadosUnidos.insertOne({ "id": "9228", "nombre": "Global Times US Edition" })
db.estadosUnidos.insertOne({ "id": "9vyc", "nombre": "Globe" })
db.estadosUnidos.insertOne({ "id": "9ge2", "nombre": "Golf Vacations" })
db.estadosUnidos.insertOne({ "id": "0196", "nombre": "Gorizont" })
db.estadosUnidos.insertOne({ "id": "9i05", "nombre": "Gotham" })
db.estadosUnidos.insertOne({ "id": "9fgr", "nombre": "Greenwich Time" })
db.estadosUnidos.insertOne({ "id": "9fgt", "nombre": "Greenwich Time (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9554", "nombre": "Guitar Techniques" })
db.estadosUnidos.insertOne({ "id": "9546", "nombre": "Guitarist" })
db.estadosUnidos.insertOne({ "id": "9515", "nombre": "Gulf &amp; Main" })
db.estadosUnidos.insertOne({ "id": "2699", "nombre": "Haiti Liberte" })
db.estadosUnidos.insertOne({ "id": "7374", "nombre": "Hamilton Journal News" })
db.estadosUnidos.insertOne({ "id": "9hzx", "nombre": "Hamptons Magazine" })
db.estadosUnidos.insertOne({ "id": "9kyr", "nombre": "Hartford Courant" })
db.estadosUnidos.insertOne({ "id": "9kyu", "nombre": "Hartford Courant (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9jd9", "nombre": "Health Data Management" })
db.estadosUnidos.insertOne({ "id": "9g79", "nombre": "Highlights (U.S. Edition)" })
db.estadosUnidos.insertOne({ "id": "9g78", "nombre": "Highlights Hello" })
db.estadosUnidos.insertOne({ "id": "9g77", "nombre": "Highlights High Five (Bilingual Edition)" })
db.estadosUnidos.insertOne({ "id": "9g76", "nombre": "Highlights High Five (U.S. Edition)" })
db.estadosUnidos.insertOne({ "id": "sare", "nombre": "Home - Santa Fe Real Estate Guide" })
db.estadosUnidos.insertOne({ "id": "9vnh", "nombre": "Home Excellence" })
db.estadosUnidos.insertOne({ "id": "9e67", "nombre": "Horse &amp; Rider" })
db.estadosUnidos.insertOne({ "id": "9i85", "nombre": "Hot Bike" })
db.estadosUnidos.insertOne({ "id": "9vj4", "nombre": "Hot Rod" })
db.estadosUnidos.insertOne({ "id": "9vjj", "nombre": "Hot Rod Deluxe" })
db.estadosUnidos.insertOne({ "id": "1084", "nombre": "Houston Chronicle" })
db.estadosUnidos.insertOne({ "id": "1210", "nombre": "Houston Chronicle Sunday" })
db.estadosUnidos.insertOne({ "id": "8331", "nombre": "Zest" })
db.estadosUnidos.insertOne({ "id": "9jd2", "nombre": "ISO &amp; Agent" })
db.estadosUnidos.insertOne({ "id": "9599", "nombre": "ImagineFX" })
db.estadosUnidos.insertOne({ "id": "9gmu", "nombre": "Imperial Valley Press" })
db.estadosUnidos.insertOne({ "id": "9hq4", "nombre": "In Touch (USA)" })
db.estadosUnidos.insertOne({ "id": "9hru", "nombre": "Inc. (USA)" })
db.estadosUnidos.insertOne({ "id": "34mh", "nombre": "Industry Leaders" })
db.estadosUnidos.insertOne({ "id": "9id1", "nombre": "Inside Weddings" })
db.estadosUnidos.insertOne({ "id": "9blk", "nombre": "International Artist" })
db.estadosUnidos.insertOne({ "id": "9ht9", "nombre": "J-14" })
db.estadosUnidos.insertOne({ "id": "9vi9", "nombre": "Jp Magazine" })
db.estadosUnidos.insertOne({ "id": "9d70", "nombre": "Just Cross Stitch" })
db.estadosUnidos.insertOne({ "id": "9vth", "nombre": "Just CrossStitch Halloween 2018" })
db.estadosUnidos.insertOne({ "id": "9hp7", "nombre": "Kent County News" })
db.estadosUnidos.insertOne({ "id": "sb32", "nombre": "Kids Summer" })
db.estadosUnidos.insertOne({ "id": "9al4", "nombre": "Knives Illustrated" })
db.estadosUnidos.insertOne({ "id": "5613", "nombre": "Korea Daily (Chicago) - Section B" })
db.estadosUnidos.insertOne({ "id": "5614", "nombre": "Korea Daily (Chicago) - Section C" })
db.estadosUnidos.insertOne({ "id": "5607", "nombre": "Korea Daily Chicago - Section A" })
db.estadosUnidos.insertOne({ "id": "9hm9", "nombre": "LUXE City Guides - Chicago" })
db.estadosUnidos.insertOne({ "id": "9hmj", "nombre": "LUXE City Guides - Los Angeles" })
db.estadosUnidos.insertOne({ "id": "9hmm", "nombre": "LUXE City Guides - Miami" })
db.estadosUnidos.insertOne({ "id": "9hmp", "nombre": "LUXE City Guides - New York" })
db.estadosUnidos.insertOne({ "id": "2078", "nombre": "La Opinión" })
db.estadosUnidos.insertOne({ "id": "2087", "nombre": "La Opinión de la Bahía" })
db.estadosUnidos.insertOne({ "id": "2080", "nombre": "La Prensa - Orlando" })
db.estadosUnidos.insertOne({ "id": "2091", "nombre": "La Raza Chicago" })
db.estadosUnidos.insertOne({ "id": "9576", "nombre": "La Semana" })
db.estadosUnidos.insertOne({ "id": "59au", "nombre": "Las Vegas Chinese Magazine" })
db.estadosUnidos.insertOne({ "id": "59at", "nombre": "Las Vegas Chinese Newspaper" })
db.estadosUnidos.insertOne({ "id": "1075", "nombre": "Las Vegas Review-Journal" })
db.estadosUnidos.insertOne({ "id": "9c41", "nombre": "Las Vegas Review-Journal (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9als", "nombre": "Ledger-Enquirer" })
db.estadosUnidos.insertOne({ "id": "9gvx", "nombre": "Ledger-Enquirer (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9aly", "nombre": "Lexington Herald-Leader" })
db.estadosUnidos.insertOne({ "id": "9ane", "nombre": "Lexington Herald-Leader (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9ht3", "nombre": "Life &amp; Style Weekly" })
db.estadosUnidos.insertOne({ "id": "9609", "nombre": "Linux Format" })
db.estadosUnidos.insertOne({ "id": "9fbh", "nombre": "Lodi News-Sentinel" })
db.estadosUnidos.insertOne({ "id": "9e85", "nombre": "Log Home Living" })
db.estadosUnidos.insertOne({ "id": "9f54", "nombre": "Lonely Planet (UK)" })
db.estadosUnidos.insertOne({ "id": "9vl5", "nombre": "Lonely Planet Magazine (US)" })
db.estadosUnidos.insertOne({ "id": "9hzy", "nombre": "Los Angeles Confidential" })
db.estadosUnidos.insertOne({ "id": "1156", "nombre": "Los Angeles Times" })
db.estadosUnidos.insertOne({ "id": "9547", "nombre": "Love Patchwork &amp; Quilting" })
db.estadosUnidos.insertOne({ "id": "9vhx", "nombre": "Low Rider" })
db.estadosUnidos.insertOne({ "id": "9hv8", "nombre": "LuxeGetaways" })
db.estadosUnidos.insertOne({ "id": "9vhl", "nombre": "MSC Buon Gusto" })
db.estadosUnidos.insertOne({ "id": "9548", "nombre": "Mac Format" })
db.estadosUnidos.insertOne({ "id": "9vgp", "nombre": "Macworld (USA)" })
db.estadosUnidos.insertOne({ "id": "9a45", "nombre": "Mac|Life" })
db.estadosUnidos.insertOne({ "id": "9i63", "nombre": "Marlin" })
db.estadosUnidos.insertOne({ "id": "9hnk", "nombre": "Maryland Independent" })
db.estadosUnidos.insertOne({ "id": "9hp4", "nombre": "Southern Maryland Automotive Trends" })
db.estadosUnidos.insertOne({ "id": "9g13", "nombre": "Marysville Appeal-Democrat    " })
db.estadosUnidos.insertOne({ "id": "9g93", "nombre": "Maxim" })
db.estadosUnidos.insertOne({ "id": "9a47", "nombre": "Maximum PC" })
db.estadosUnidos.insertOne({ "id": "8494", "nombre": "McDonald County Press" })
db.estadosUnidos.insertOne({ "id": "9kgv", "nombre": "Mein Amerika" })
db.estadosUnidos.insertOne({ "id": "9vyf", "nombre": "Men's Journal" })
db.estadosUnidos.insertOne({ "id": "9am4", "nombre": "Merced Sun-Star" })
db.estadosUnidos.insertOne({ "id": "9anf", "nombre": "Merced Sun-Star (Saturday)" })
db.estadosUnidos.insertOne({ "id": "1023", "nombre": "Miami Herald" })
db.estadosUnidos.insertOne({ "id": "9gvy", "nombre": "Miami Herald (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9hzz", "nombre": "Michigan Avenue" })
db.estadosUnidos.insertOne({ "id": "say7", "nombre": "Milwaukee Health" })
db.estadosUnidos.insertOne({ "id": "9b80", "nombre": "Milwaukee Journal Sentinel" })
db.estadosUnidos.insertOne({ "id": "9j25", "nombre": "Milwaukee Magazine" })
db.estadosUnidos.insertOne({ "id": "9ic6", "nombre": "Model Airplane News" })
db.estadosUnidos.insertOne({ "id": "s905", "nombre": "100 Top Hospitals" })
db.estadosUnidos.insertOne({ "id": "7236", "nombre": "Modern Healthcare" })
db.estadosUnidos.insertOne({ "id": "s917", "nombre": "Modern Healthcare - Supreme Court / ACA Special Edition" })
db.estadosUnidos.insertOne({ "id": "9vka", "nombre": "Mopar Muscle" })
db.estadosUnidos.insertOne({ "id": "9vi0", "nombre": "Motor Trend" })
db.estadosUnidos.insertOne({ "id": "9i86", "nombre": "Motorcyclist" })
db.estadosUnidos.insertOne({ "id": "t916", "nombre": "Britain's 50 Best Trail Centres" })
db.estadosUnidos.insertOne({ "id": "9550", "nombre": "Mountain Biking UK" })
db.estadosUnidos.insertOne({ "id": "9vyg", "nombre": "Muscle &amp; Fitness USA" })
db.estadosUnidos.insertOne({ "id": "9vhr", "nombre": "Muscle Car Review" })
db.estadosUnidos.insertOne({ "id": "9vj5", "nombre": "Muscle Mustangs &amp; Fast Fords" })
db.estadosUnidos.insertOne({ "id": "9vkb", "nombre": "Mustang Monthly" })
db.estadosUnidos.insertOne({ "id": "9wtw", "nombre": "My Yuma Home" })
db.estadosUnidos.insertOne({ "id": "9vyb", "nombre": "National Enquirer" })
db.estadosUnidos.insertOne({ "id": "9jd1", "nombre": "National Mortgage News" })
db.estadosUnidos.insertOne({ "id": "9bll", "nombre": "Native American Art" })
db.estadosUnidos.insertOne({ "id": "909g", "nombre": "New Haven Register (New Haven, CT)" })
db.estadosUnidos.insertOne({ "id": "909d", "nombre": "New Haven Register (Sunday) (New Haven, CT)" })
db.estadosUnidos.insertOne({ "id": "1024", "nombre": "New York Daily News" })
db.estadosUnidos.insertOne({ "id": "1245", "nombre": "New York Post" })
db.estadosUnidos.insertOne({ "id": "9hp8", "nombre": "Newark Post" })
db.estadosUnidos.insertOne({ "id": "9060", "nombre": "News-Herald (Perkasie, PA)" })
db.estadosUnidos.insertOne({ "id": "1512", "nombre": "Newspapers &amp; Technology Magazine" })
db.estadosUnidos.insertOne({ "id": "9fc6", "nombre": "Newsweek" })
db.estadosUnidos.insertOne({ "id": "eb24", "nombre": "Newsweek en Español" })
db.estadosUnidos.insertOne({ "id": "8899", "nombre": "Northern Berks Patriot Item" })
db.estadosUnidos.insertOne({ "id": "8475", "nombre": "Northwest Arkansas Democrat-Gazette" })
db.estadosUnidos.insertOne({ "id": "9vya", "nombre": "OK! (USA)" })
db.estadosUnidos.insertOne({ "id": "9i02", "nombre": "Ocean Drive" })
db.estadosUnidos.insertOne({ "id": "9e62", "nombre": "Old House Journal" })
db.estadosUnidos.insertOne({ "id": "7068", "nombre": "Orlando Sentinel" })
db.estadosUnidos.insertOne({ "id": "9amw", "nombre": "Orlando Sentinel (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9i47", "nombre": "Outdoor Life" })
db.estadosUnidos.insertOne({ "id": "9e90", "nombre": "Oxygen" })
db.estadosUnidos.insertOne({ "id": "9a49", "nombre": "PC GAMER (US)" })
db.estadosUnidos.insertOne({ "id": "9vgq", "nombre": "PCWorld (USA)" })
db.estadosUnidos.insertOne({ "id": "9b88", "nombre": "Packer Plus" })
db.estadosUnidos.insertOne({ "id": "9a02", "nombre": "Papercraft Inspirations" })
db.estadosUnidos.insertOne({ "id": "6162", "nombre": "Pasatiempo" })
db.estadosUnidos.insertOne({ "id": "9gpg", "nombre": "Pasmag (USA)" })
db.estadosUnidos.insertOne({ "id": "9e60", "nombre": "Passage Maker" })
db.estadosUnidos.insertOne({ "id": "9g20", "nombre": "Pawtucket Times" })
db.estadosUnidos.insertOne({ "id": "9640", "nombre": "Performance Vauxhall" })
db.estadosUnidos.insertOne({ "id": "8369", "nombre": "Philadelphia Daily News" })
db.estadosUnidos.insertOne({ "id": "9i01", "nombre": "Philadelphia Style" })
db.estadosUnidos.insertOne({ "id": "9536", "nombre": "Photo Plus" })
db.estadosUnidos.insertOne({ "id": "1313", "nombre": "Pittsburgh Post-Gazette" })
db.estadosUnidos.insertOne({ "id": "9ic4", "nombre": "Poets and Writers" })
db.estadosUnidos.insertOne({ "id": "9i48", "nombre": "Popular Science" })
db.estadosUnidos.insertOne({ "id": "9g14", "nombre": "Porterville Recorder" })
db.estadosUnidos.insertOne({ "id": "9498", "nombre": "Porthole Cruise Magazine" })
db.estadosUnidos.insertOne({ "id": "9357", "nombre": "Post-Tribune" })
db.estadosUnidos.insertOne({ "id": "9e56", "nombre": "Power &amp; Motor Yacht" })
db.estadosUnidos.insertOne({ "id": "9e66", "nombre": "Practical Horseman" })
db.estadosUnidos.insertOne({ "id": "9596", "nombre": "Procycling" })
db.estadosUnidos.insertOne({ "id": "9d71", "nombre": "Quilter's World" })
db.estadosUnidos.insertOne({ "id": "9je9", "nombre": "Quilter's World - Quilting for Christmas" })
db.estadosUnidos.insertOne({ "id": "9gvu", "nombre": "Quilter's World - Quilts You Can Make in a Day" })
db.estadosUnidos.insertOne({ "id": "9kgl", "nombre": "Quilter's World - Springtime Quilts May 2019" })
db.estadosUnidos.insertOne({ "id": "9vwb", "nombre": "Quilters World - Autumn Colors " })
db.estadosUnidos.insertOne({ "id": "9hta", "nombre": "QuizFest" })
db.estadosUnidos.insertOne({ "id": "9id5", "nombre": "RC Car Action" })
db.estadosUnidos.insertOne({ "id": "9516", "nombre": "RSWLiving" })
db.estadosUnidos.insertOne({ "id": "9kny", "nombre": "Raise Vegan" })
db.estadosUnidos.insertOne({ "id": "7477", "nombre": "Rappahannock News" })
db.estadosUnidos.insertOne({ "id": "9hp9", "nombre": "Record Observer" })
db.estadosUnidos.insertOne({ "id": "1153", "nombre": "Red Eye Chicago" })
db.estadosUnidos.insertOne({ "id": "9if7", "nombre": "Reminisce" })
db.estadosUnidos.insertOne({ "id": "9ge1", "nombre": "Retreat" })
db.estadosUnidos.insertOne({ "id": "9a03", "nombre": "Rhythm" })
db.estadosUnidos.insertOne({ "id": "1097", "nombre": "Richmond Times-Dispatch" })
db.estadosUnidos.insertOne({ "id": "1124", "nombre": "Richmond Times-Dispatch Weekend" })
db.estadosUnidos.insertOne({ "id": "9vhi", "nombre": "Robb Report (USA)" })
db.estadosUnidos.insertOne({ "id": "9wsp", "nombre": "Rolling Stone" })
db.estadosUnidos.insertOne({ "id": "9al6", "nombre": "Romantic Homes" })
db.estadosUnidos.insertOne({ "id": "1343", "nombre": "Rome News-Tribune" })
db.estadosUnidos.insertOne({ "id": "9hyz", "nombre": "Rustic Weddings" })
db.estadosUnidos.insertOne({ "id": "9e57", "nombre": "SAIL" })
db.estadosUnidos.insertOne({ "id": "9i87", "nombre": "SAVEUR" })
db.estadosUnidos.insertOne({ "id": "9556", "nombre": "SFX" })
db.estadosUnidos.insertOne({ "id": "9e96", "nombre": "SKI" })
db.estadosUnidos.insertOne({ "id": "9j67", "nombre": "STC Magazine" })
db.estadosUnidos.insertOne({ "id": "9i92", "nombre": "Sailing World" })
db.estadosUnidos.insertOne({ "id": "9i91", "nombre": "Saltwater Sportsman" })
db.estadosUnidos.insertOne({ "id": "9jg3", "nombre": "San Antonio Express-News" })
db.estadosUnidos.insertOne({ "id": "9jg4", "nombre": "San Antonio Express-News (Sunday)" })
db.estadosUnidos.insertOne({ "id": "1033", "nombre": "San Francisco Chronicle" })
db.estadosUnidos.insertOne({ "id": "909c", "nombre": "San Francisco Chronicle (Sunday)" })
db.estadosUnidos.insertOne({ "id": "909f", "nombre": "San Francisco Chronicle - Late Edition (Sunday)" })
db.estadosUnidos.insertOne({ "id": "8342", "nombre": "San Francisco Chronicle Late Edition" })
db.estadosUnidos.insertOne({ "id": "9d76", "nombre": "Santa Fe New Mexican" })
db.estadosUnidos.insertOne({ "id": "savz", "nombre": "Santa Fe New Mexican - Chamber of Commerce Directory" })
db.estadosUnidos.insertOne({ "id": "sb29", "nombre": "Santa Fe New Mexican - Healthy Living" })
db.estadosUnidos.insertOne({ "id": "9i89", "nombre": "Scuba Diving" })
db.estadosUnidos.insertOne({ "id": "9hz5", "nombre": "Seabourn Club Herald" })
db.estadosUnidos.insertOne({ "id": "9a40", "nombre": "Serve Daily" })
db.estadosUnidos.insertOne({ "id": "8496", "nombre": "Siloam Springs Herald Leader" })
db.estadosUnidos.insertOne({ "id": "9if4", "nombre": "Simple &amp; Delicious" })
db.estadosUnidos.insertOne({ "id": "9a04", "nombre": "Simply Crochet" })
db.estadosUnidos.insertOne({ "id": "9598", "nombre": "Simply Knitting" })
db.estadosUnidos.insertOne({ "id": "9ghl", "nombre": "Smithsonian Magazine" })
db.estadosUnidos.insertOne({ "id": "9gmt", "nombre": "Sno-Dak News" })
db.estadosUnidos.insertOne({ "id": "9vye", "nombre": "Soap Opera Digest" })
db.estadosUnidos.insertOne({ "id": "9059", "nombre": "Souderton Independent" })
db.estadosUnidos.insertOne({ "id": "9vhy", "nombre": "Sound &amp; Vision" })
db.estadosUnidos.insertOne({ "id": "9e93", "nombre": "Soundings" })
db.estadosUnidos.insertOne({ "id": "ef30", "nombre": "South County Best" })
db.estadosUnidos.insertOne({ "id": "9amk", "nombre": "South Florida Sun-Sentinel (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9gvz", "nombre": "South Florida Sun-Sentinel Palm Beach (Sunday)" })
db.estadosUnidos.insertOne({ "id": "1866", "nombre": "South Florida Times" })
db.estadosUnidos.insertOne({ "id": "9i64", "nombre": "Sport Fishing" })
db.estadosUnidos.insertOne({ "id": "7376", "nombre": "Springfield News-Sun" })
db.estadosUnidos.insertOne({ "id": "9fgw", "nombre": "Stamford Advocate" })
db.estadosUnidos.insertOne({ "id": "9fgx", "nombre": "Stamford Advocate (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9vy9", "nombre": "Star (USA)" })
db.estadosUnidos.insertOne({ "id": "1246", "nombre": "Star-Telegram" })
db.estadosUnidos.insertOne({ "id": "9alz", "nombre": "Star-Telegram (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9huk", "nombre": "Starkville Daily News" })
db.estadosUnidos.insertOne({ "id": "9vj7", "nombre": "Stereophile" })
db.estadosUnidos.insertOne({ "id": "9i90", "nombre": "Street Chopper" })
db.estadosUnidos.insertOne({ "id": "9vj3", "nombre": "Street Rodder" })
db.estadosUnidos.insertOne({ "id": "9al8", "nombre": "Street Trucks" })
db.estadosUnidos.insertOne({ "id": "6040", "nombre": "Community Marketplace - Central West" })
db.estadosUnidos.insertOne({ "id": "6045", "nombre": "Community Marketplace - Northeast" })
db.estadosUnidos.insertOne({ "id": "6037", "nombre": "Community Marketplace - Northwest" })
db.estadosUnidos.insertOne({ "id": "6035", "nombre": "Community Marketplace - South Broward" })
db.estadosUnidos.insertOne({ "id": "6049", "nombre": "Homespot - Broward East" })
db.estadosUnidos.insertOne({ "id": "6046", "nombre": "Showtime - Broward" })
db.estadosUnidos.insertOne({ "id": "1975", "nombre": "Sun Sentinel Broward Edition" })
db.estadosUnidos.insertOne({ "id": "6038", "nombre": "Community Marketplace - Palm Central" })
db.estadosUnidos.insertOne({ "id": "6036", "nombre": "Community Marketplace - Palm South" })
db.estadosUnidos.insertOne({ "id": "6047", "nombre": "Showtime - Palm Beach" })
db.estadosUnidos.insertOne({ "id": "6093", "nombre": "Sun Sentinel Palm Beach Edition" })
db.estadosUnidos.insertOne({ "id": "9hpa", "nombre": "Sunday Star" })
db.estadosUnidos.insertOne({ "id": "9vj8", "nombre": "Super Chevy" })
db.estadosUnidos.insertOne({ "id": "9vjk", "nombre": "Super Street" })
db.estadosUnidos.insertOne({ "id": "9559", "nombre": "T3" })
db.estadosUnidos.insertOne({ "id": "9j90", "nombre": "Tactical World" })
db.estadosUnidos.insertOne({ "id": "7089", "nombre": "Tampa Bay Times" })
db.estadosUnidos.insertOne({ "id": "9if1", "nombre": "Taste of Home" })
db.estadosUnidos.insertOne({ "id": "9aae", "nombre": "Tasty Vegan Style" })
db.estadosUnidos.insertOne({ "id": "9vxy", "nombre": "Techlife News" })
db.estadosUnidos.insertOne({ "id": "34km", "nombre": "Technowize Magazine" })
db.estadosUnidos.insertOne({ "id": "9kyg", "nombre": "Tempo" })
db.estadosUnidos.insertOne({ "id": "9050", "nombre": "Texarkana Gazette" })
db.estadosUnidos.insertOne({ "id": "8585", "nombre": "The Abington Suburban" })
db.estadosUnidos.insertOne({ "id": "9071", "nombre": "The Advance of Bucks County" })
db.estadosUnidos.insertOne({ "id": "9056", "nombre": "The Ambler Gazette" })
db.estadosUnidos.insertOne({ "id": "1012", "nombre": "The Arizona Republic" })
db.estadosUnidos.insertOne({ "id": "8234", "nombre": "The Atlanta Journal-Constitution" })
db.estadosUnidos.insertOne({ "id": "9hp2", "nombre": "The Avenue News" })
db.estadosUnidos.insertOne({ "id": "9alr", "nombre": "The Beaufort Gazette" })
db.estadosUnidos.insertOne({ "id": "9amv", "nombre": "The Beaufort Gazette (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9amb", "nombre": "The Bellingham Herald" })
db.estadosUnidos.insertOne({ "id": "9amp", "nombre": "The Bellingham Herald (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9jd3", "nombre": "The Bond Buyer" })
db.estadosUnidos.insertOne({ "id": "8895", "nombre": "The Boyertown Area Times" })
db.estadosUnidos.insertOne({ "id": "9alv", "nombre": "The Bradenton Herald" })
db.estadosUnidos.insertOne({ "id": "9an1", "nombre": "The Bradenton Herald (Sunday)" })
db.estadosUnidos.insertOne({ "id": "1733", "nombre": "The Buffalo News" })
db.estadosUnidos.insertOne({ "id": "9hp4", "nombre": "Southern Maryland Automotive Trends" })
db.estadosUnidos.insertOne({ "id": "9hng", "nombre": "The Calvert Recorder" })
db.estadosUnidos.insertOne({ "id": "9kyt", "nombre": "The Capital" })
db.estadosUnidos.insertOne({ "id": "1592", "nombre": "The Catoosa County News" })
db.estadosUnidos.insertOne({ "id": "1155", "nombre": "The Charlotte Observer" })
db.estadosUnidos.insertOne({ "id": "9vtb", "nombre": "The Charlotte Observer (Sunday)" })
db.estadosUnidos.insertOne({ "id": "1010", "nombre": "The Christian Science Monitor" })
db.estadosUnidos.insertOne({ "id": "v312", "nombre": "TV Weekly" })
db.estadosUnidos.insertOne({ "id": "8108", "nombre": "The Citizens' Voice" })
db.estadosUnidos.insertOne({ "id": "1206", "nombre": "The Columbus Dispatch" })
db.estadosUnidos.insertOne({ "id": "1779", "nombre": "Go Memphis" })
db.estadosUnidos.insertOne({ "id": "1416", "nombre": "The Commercial Appeal" })
db.estadosUnidos.insertOne({ "id": "8897", "nombre": "The Community Connection" })
db.estadosUnidos.insertOne({ "id": "1151", "nombre": "The Dallas Morning News" })
db.estadosUnidos.insertOne({ "id": "6265", "nombre": "Home Source" })
db.estadosUnidos.insertOne({ "id": "6287", "nombre": "Night &amp; Day" })
db.estadosUnidos.insertOne({ "id": "6293", "nombre": "Sound &amp; Country" })
db.estadosUnidos.insertOne({ "id": "1995", "nombre": "The Day" })
db.estadosUnidos.insertOne({ "id": "7769", "nombre": "The Denver Post" })
db.estadosUnidos.insertOne({ "id": "1454", "nombre": "The Detroit News" })
db.estadosUnidos.insertOne({ "id": "9hp3", "nombre": "The Dundalk Eagle" })
db.estadosUnidos.insertOne({ "id": "9hp6", "nombre": "The Enquire-Gazette" })
db.estadosUnidos.insertOne({ "id": "9hp4", "nombre": "Southern Maryland Automotive Trends" })
db.estadosUnidos.insertOne({ "id": "9hnj", "nombre": "The Enterprise" })
db.estadosUnidos.insertOne({ "id": "9if6", "nombre": "The Family Handyman" })
db.estadosUnidos.insertOne({ "id": "9am5", "nombre": "The Fresno Bee" })
db.estadosUnidos.insertOne({ "id": "9vvx", "nombre": "The Fresno Bee (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9wap", "nombre": "The Guardian (USA)" })
db.estadosUnidos.insertOne({ "id": "34mj", "nombre": "The HR Digest" })
db.estadosUnidos.insertOne({ "id": "v313", "nombre": "TV Weekly" })
db.estadosUnidos.insertOne({ "id": "8099", "nombre": "The Hazleton Standard-Speaker" })
db.estadosUnidos.insertOne({ "id": "9vtg", "nombre": "The Herald (Rock Hill)" })
db.estadosUnidos.insertOne({ "id": "9vtc", "nombre": "The Herald Sun" })
db.estadosUnidos.insertOne({ "id": "9amq", "nombre": "The Herald-Sun (Sunday)" })
db.estadosUnidos.insertOne({ "id": "sfel", "nombre": "The Hockey News - Playoff Preview (USA)" })
db.estadosUnidos.insertOne({ "id": "9am1", "nombre": "The Idaho Statesman" })
db.estadosUnidos.insertOne({ "id": "9am8", "nombre": "The Idaho Statesman (Sunday)" })
db.estadosUnidos.insertOne({ "id": "sats", "nombre": "The Insider" })
db.estadosUnidos.insertOne({ "id": "9ggl", "nombre": "The Iowa Review" })
db.estadosUnidos.insertOne({ "id": "9alq", "nombre": "The Island Packet" })
db.estadosUnidos.insertOne({ "id": "9amu", "nombre": "The Island Packet (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9170", "nombre": "The Jewish Voice" })
db.estadosUnidos.insertOne({ "id": "9alw", "nombre": "The Kansas City Star " })
db.estadosUnidos.insertOne({ "id": "1208", "nombre": "The Kansas City Star (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9hnf", "nombre": "The Kent Island Bay Times" })
db.estadosUnidos.insertOne({ "id": "9558", "nombre": "The Knitter" })
db.estadosUnidos.insertOne({ "id": "5501", "nombre": "The Korea Daily" })
db.estadosUnidos.insertOne({ "id": "9ic1", "nombre": "The Maui News" })
db.estadosUnidos.insertOne({ "id": "9kjy", "nombre": "The Maui News - Sunday edition " })
db.estadosUnidos.insertOne({ "id": "8484", "nombre": "The Mercury (Pottstown, PA)" })
db.estadosUnidos.insertOne({ "id": "1013", "nombre": "The Mercury News" })
db.estadosUnidos.insertOne({ "id": "1036", "nombre": "The Mercury News Weekend" })
db.estadosUnidos.insertOne({ "id": "8482", "nombre": "The Middletown Press (Middletown, CT)" })
db.estadosUnidos.insertOne({ "id": "9am3", "nombre": "The Modesto Bee" })
db.estadosUnidos.insertOne({ "id": "9amx", "nombre": "The Modesto Bee (Sunday)" })
db.estadosUnidos.insertOne({ "id": "1526", "nombre": "The Morning Call" })
db.estadosUnidos.insertOne({ "id": "9kyv", "nombre": "The Morning Call (Sunday)" })
db.estadosUnidos.insertOne({ "id": "8544", "nombre": "The Morning Journal (Lorain, OH)" })
db.estadosUnidos.insertOne({ "id": "9khf", "nombre": "The New York Review of Books" })
db.estadosUnidos.insertOne({ "id": "9vta", "nombre": "The News &amp; Observer" })
db.estadosUnidos.insertOne({ "id": "9am7", "nombre": "The News &amp; Observer (Sunday)" })
db.estadosUnidos.insertOne({ "id": "8486", "nombre": "The News Herald (Willoughby, OH)" })
db.estadosUnidos.insertOne({ "id": "9am9", "nombre": "The News Tribune" })
db.estadosUnidos.insertOne({ "id": "9fgu", "nombre": "The News-Times" })
db.estadosUnidos.insertOne({ "id": "9fgv", "nombre": "The News-Times (Sunday)" })
db.estadosUnidos.insertOne({ "id": "909e", "nombre": "The Norwalk Hour" })
db.estadosUnidos.insertOne({ "id": "1682", "nombre": "The Oklahoman" })
db.estadosUnidos.insertOne({ "id": "9k05", "nombre": "The Oklahoman (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9vvw", "nombre": "The Olympian" })
db.estadosUnidos.insertOne({ "id": "8523", "nombre": "The Oneida Daily Dispatch (Oneida, NY)" })
db.estadosUnidos.insertOne({ "id": "ef31", "nombre": "The Outpost" })
db.estadosUnidos.insertOne({ "id": "1014", "nombre": "The Philadelphia Inquirer" })
db.estadosUnidos.insertOne({ "id": "1489", "nombre": "The Philadelphia Inquirer (South Jersey edition)" })
db.estadosUnidos.insertOne({ "id": "8902", "nombre": "The Phoenix" })
db.estadosUnidos.insertOne({ "id": "8128", "nombre": "The Progress-Index" })
db.estadosUnidos.insertOne({ "id": "8557", "nombre": "The Progress-Index Weekend" })
db.estadosUnidos.insertOne({ "id": "8487", "nombre": "The Record (Troy, NY)" })
db.estadosUnidos.insertOne({ "id": "8421", "nombre": "The Register Citizen (Torrington, CT)" })
db.estadosUnidos.insertOne({ "id": "8422", "nombre": "The Reporter (Lansdale, PA)" })
db.estadosUnidos.insertOne({ "id": "8539", "nombre": "The Republican Herald" })
db.estadosUnidos.insertOne({ "id": "9b02", "nombre": "This Weekend" })
db.estadosUnidos.insertOne({ "id": "9070", "nombre": "The Review" })
db.estadosUnidos.insertOne({ "id": "9am2", "nombre": "The Sacramento Bee" })
db.estadosUnidos.insertOne({ "id": "1085", "nombre": "The Sacramento Bee (Sunday)" })
db.estadosUnidos.insertOne({ "id": "8488", "nombre": "The Saratogian (Saratoga, NY)" })
db.estadosUnidos.insertOne({ "id": "8971", "nombre": "HER - Hot Springs" })
db.estadosUnidos.insertOne({ "id": "8970", "nombre": "The Sentinel-Record" })
db.estadosUnidos.insertOne({ "id": "6703", "nombre": "The Signal" })
db.estadosUnidos.insertOne({ "id": "8901", "nombre": "The Southern Berks News" })
db.estadosUnidos.insertOne({ "id": "1579", "nombre": "The Spokesman-Review (Spokane)" })
db.estadosUnidos.insertOne({ "id": "9a44", "nombre": "The Standard Journal" })
db.estadosUnidos.insertOne({ "id": "9hnh", "nombre": "The Star Democrat" })
db.estadosUnidos.insertOne({ "id": "9vtd", "nombre": "The State" })
db.estadosUnidos.insertOne({ "id": "9amr", "nombre": "The State (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9alu", "nombre": "The Sun Herald" })
db.estadosUnidos.insertOne({ "id": "9an2", "nombre": "The Sun Herald (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9vtf", "nombre": "The Sun News" })
db.estadosUnidos.insertOne({ "id": "9amt", "nombre": "The Sun News (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9vxv", "nombre": "Enchanted Homes" })
db.estadosUnidos.insertOne({ "id": "9vwy", "nombre": "Fall Festivals" })
db.estadosUnidos.insertOne({ "id": "9kyf", "nombre": "The Taos News" })
db.estadosUnidos.insertOne({ "id": "9xuh", "nombre": "The Taos News - 24 hours" })
db.estadosUnidos.insertOne({ "id": "9wb3", "nombre": "The Taos News - Dining Out" })
db.estadosUnidos.insertOne({ "id": "9xw2", "nombre": "The Taos News - Discover Taos Summer/Fall 2019" })
db.estadosUnidos.insertOne({ "id": "9xvc", "nombre": "The Taos News - Taos Gallery Guide" })
db.estadosUnidos.insertOne({ "id": "9xur", "nombre": "The Taos News - Taos Woman 2019 " })
db.estadosUnidos.insertOne({ "id": "9e50", "nombre": "The Team Roping Journal" })
db.estadosUnidos.insertOne({ "id": "9alt", "nombre": "The Telegraph (Macon)" })
db.estadosUnidos.insertOne({ "id": "9an3", "nombre": "The Telegraph (Macon) (Sunday)" })
db.estadosUnidos.insertOne({ "id": "8495", "nombre": "The Times (Northeast Benton County)" })
db.estadosUnidos.insertOne({ "id": "8423", "nombre": "The Times Herald (Norristown, PA)" })
db.estadosUnidos.insertOne({ "id": "9e42", "nombre": "GameFace" })
db.estadosUnidos.insertOne({ "id": "8167", "nombre": "Home Source" })
db.estadosUnidos.insertOne({ "id": "8114", "nombre": "TV Weekly" })
db.estadosUnidos.insertOne({ "id": "7523", "nombre": "The Times-Tribune" })
db.estadosUnidos.insertOne({ "id": "8424", "nombre": "The Trentonian (Trenton, NJ)" })
db.estadosUnidos.insertOne({ "id": "8584", "nombre": "The Triboro Banner" })
db.estadosUnidos.insertOne({ "id": "9am6", "nombre": "The Tribune (SLO)" })
db.estadosUnidos.insertOne({ "id": "9vwo", "nombre": "The Tribune (SLO) (Sunday)" })
db.estadosUnidos.insertOne({ "id": "8586", "nombre": "The Valley Advantage" })
db.estadosUnidos.insertOne({ "id": "1047", "nombre": "The Washington Post" })
db.estadosUnidos.insertOne({ "id": "1058", "nombre": "The Washington Post Sunday" })
db.estadosUnidos.insertOne({ "id": "1062", "nombre": "The Washington Times Daily" })
db.estadosUnidos.insertOne({ "id": "1002", "nombre": "The Washington Times Weekly" })
db.estadosUnidos.insertOne({ "id": "9hpq", "nombre": "The Week (US)" })
db.estadosUnidos.insertOne({ "id": "8493", "nombre": "The Weekly Vista" })
db.estadosUnidos.insertOne({ "id": "9alx", "nombre": "The Wichita Eagle" })
db.estadosUnidos.insertOne({ "id": "9an4", "nombre": "The Wichita Eagle (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9e61", "nombre": "Timber Home Living" })
db.estadosUnidos.insertOne({ "id": "9057", "nombre": "Times Chronicle &amp; Public Spirit" })
db.estadosUnidos.insertOne({ "id": "9517", "nombre": "Times of the Islands" })
db.estadosUnidos.insertOne({ "id": "9hnl", "nombre": "Times-Record" })
db.estadosUnidos.insertOne({ "id": "9f58", "nombre": "Top Gear (UK)" })
db.estadosUnidos.insertOne({ "id": "9487", "nombre": "Total Film" })
db.estadosUnidos.insertOne({ "id": "9637", "nombre": "Total Guitar" })
db.estadosUnidos.insertOne({ "id": "9vz6", "nombre": "Tradiciones Heroes " })
db.estadosUnidos.insertOne({ "id": "9vxu", "nombre": "Tradiciones Leyendas" })
db.estadosUnidos.insertOne({ "id": "9vz1", "nombre": "Tradiciones: Artes" })
db.estadosUnidos.insertOne({ "id": "9kha", "nombre": "Travel Guide to California" })
db.estadosUnidos.insertOne({ "id": "9khb", "nombre": "Travel Guide to Florida" })
db.estadosUnidos.insertOne({ "id": "9j11", "nombre": "Traveling Minds " })
db.estadosUnidos.insertOne({ "id": "9kgr", "nombre": "Tread" })
db.estadosUnidos.insertOne({ "id": "8900", "nombre": "Tri County Record" })
db.estadosUnidos.insertOne({ "id": "9ama", "nombre": "Tri-City Herald" })
db.estadosUnidos.insertOne({ "id": "9vws", "nombre": "Tri-City Herald (Sunday)" })
db.estadosUnidos.insertOne({ "id": "9gs1", "nombre": "Trillions" })
db.estadosUnidos.insertOne({ "id": "9vj6", "nombre": "Truck Trend" })
db.estadosUnidos.insertOne({ "id": "9vhz", "nombre": "Truckin" })
db.estadosUnidos.insertOne({ "id": "8038", "nombre": "Tulsa World" })
db.estadosUnidos.insertOne({ "id": "8107", "nombre": "World of Homes" })
db.estadosUnidos.insertOne({ "id": "9vyd", "nombre": "US Weekly" })
db.estadosUnidos.insertOne({ "id": "1021", "nombre": "USA TODAY International Edition" })
db.estadosUnidos.insertOne({ "id": "6972", "nombre": "USA TODAY Sports Weekly" })
db.estadosUnidos.insertOne({ "id": "1152", "nombre": "USA TODAY US Edition" })
db.estadosUnidos.insertOne({ "id": "9kka", "nombre": "Upscale Living Magazine" })
db.estadosUnidos.insertOne({ "id": "0288", "nombre": "V Novom Svete" })
db.estadosUnidos.insertOne({ "id": "eb84", "nombre": "VOGUE Latinoamerica" })
db.estadosUnidos.insertOne({ "id": "9vhk", "nombre": "Variety" })
db.estadosUnidos.insertOne({ "id": "9i03", "nombre": "Vegas Magazine" })
db.estadosUnidos.insertOne({ "id": "9vjy", "nombre": "Vette" })
db.estadosUnidos.insertOne({ "id": "9hne", "nombre": "WDW Magazine" })
db.estadosUnidos.insertOne({ "id": "9vgr", "nombre": "WWD Digital Daily" })
db.estadosUnidos.insertOne({ "id": "1596", "nombre": "Walker County Messenger" })
db.estadosUnidos.insertOne({ "id": "8497", "nombre": "Washington County Enterprise-Leader" })
db.estadosUnidos.insertOne({ "id": "9gax", "nombre": "WatchTime" })
db.estadosUnidos.insertOne({ "id": "9bln", "nombre": "West of 105 Magazine" })
db.estadosUnidos.insertOne({ "id": "9blm", "nombre": "Western Art Collector" })
db.estadosUnidos.insertOne({ "id": "8498", "nombre": "Westside Eagle-Observer" })
db.estadosUnidos.insertOne({ "id": "9b05", "nombre": "Where Atlanta" })
db.estadosUnidos.insertOne({ "id": "9d58", "nombre": "Where Baltimore" })
db.estadosUnidos.insertOne({ "id": "9b89", "nombre": "Where Boston" })
db.estadosUnidos.insertOne({ "id": "9d26", "nombre": "Where Charleston" })
db.estadosUnidos.insertOne({ "id": "9b90", "nombre": "Where Charlotte" })
db.estadosUnidos.insertOne({ "id": "9b91", "nombre": "Where Chicago" })
db.estadosUnidos.insertOne({ "id": "9b92", "nombre": "Where Dallas" })
db.estadosUnidos.insertOne({ "id": "9b94", "nombre": "Where Las Vegas" })
db.estadosUnidos.insertOne({ "id": "9e74", "nombre": "Where Maui" })
db.estadosUnidos.insertOne({ "id": "9b98", "nombre": "Where Miami" })
db.estadosUnidos.insertOne({ "id": "9b95", "nombre": "Where New Orleans" })
db.estadosUnidos.insertOne({ "id": "9b96", "nombre": "Where New York" })
db.estadosUnidos.insertOne({ "id": "9e75", "nombre": "Where Oahu" })
db.estadosUnidos.insertOne({ "id": "9b97", "nombre": "Where Orlando" })
db.estadosUnidos.insertOne({ "id": "9b71", "nombre": "Where Philadelphia" })
db.estadosUnidos.insertOne({ "id": "9b72", "nombre": "Where Phoenix" })
db.estadosUnidos.insertOne({ "id": "9b73", "nombre": "Where San Francisco" })
db.estadosUnidos.insertOne({ "id": "9b74", "nombre": "Where Seattle" })
db.estadosUnidos.insertOne({ "id": "9b99", "nombre": "Where St. Louis" })
db.estadosUnidos.insertOne({ "id": "9f25", "nombre": "Where Tucson" })
db.estadosUnidos.insertOne({ "id": "9c01", "nombre": "Where Washington" })
db.estadosUnidos.insertOne({ "id": "9635", "nombre": "Windows Help &amp; Advice" })
db.estadosUnidos.insertOne({ "id": "9ht4", "nombre": "Woman's World" })
db.estadosUnidos.insertOne({ "id": "9g19", "nombre": "Woonsocket Call" })
db.estadosUnidos.insertOne({ "id": "9i95", "nombre": "Working Mother" })
db.estadosUnidos.insertOne({ "id": "5224", "nombre": "World Journal (Atlanta)" })
db.estadosUnidos.insertOne({ "id": "va12", "nombre": "World Journal (Atlanta) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "5225", "nombre": "World Journal (Boston)" })
db.estadosUnidos.insertOne({ "id": "va13", "nombre": "World Journal (Boston) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "5226", "nombre": "World Journal (Chicago)" })
db.estadosUnidos.insertOne({ "id": "va14", "nombre": "World Journal (Chicago)  - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "5232", "nombre": "World Journal (Los Angeles)" })
db.estadosUnidos.insertOne({ "id": "t652", "nombre": "World Journal (Los Angeles) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "t673", "nombre": "World Journal (Los Angles) - Regimen &amp; Beauty" })
db.estadosUnidos.insertOne({ "id": "5228", "nombre": "World Journal (New Jersey)" })
db.estadosUnidos.insertOne({ "id": "va10", "nombre": "World Journal (New Jersey) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "5207", "nombre": "World Journal (New York)" })
db.estadosUnidos.insertOne({ "id": "t645", "nombre": "World Journal (New York) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "5230", "nombre": "World Journal (San Francisco)" })
db.estadosUnidos.insertOne({ "id": "t653", "nombre": "World Journal (San Francisco) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "va15", "nombre": "World Journal (Seattle/Hawaii) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "5233", "nombre": "World Journal (Texas)" })
db.estadosUnidos.insertOne({ "id": "t654", "nombre": "World Journal (Texas) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "5227", "nombre": "World Journal (Washington DC)" })
db.estadosUnidos.insertOne({ "id": "va11", "nombre": "World Journal (Washington DC) - Weekly Supplement" })
db.estadosUnidos.insertOne({ "id": "9gle", "nombre": "Wynn Magazine" })
db.estadosUnidos.insertOne({ "id": "9a48", "nombre": "XBox: The Official Magazine (US)" })
db.estadosUnidos.insertOne({ "id": "9i96", "nombre": "Yachting" })
db.estadosUnidos.insertOne({ "id": "9e58", "nombre": "Yachts International" })
db.estadosUnidos.insertOne({ "id": "9e91", "nombre": "Yoga Journal" })
db.estadosUnidos.insertOne({ "id": "ef28", "nombre": "Yuma Bike Map" })
db.estadosUnidos.insertOne({ "id": "9g0b", "nombre": "Raising Yuma Families" })
db.estadosUnidos.insertOne({ "id": "9g0c", "nombre": "Southwest Living" })
db.estadosUnidos.insertOne({ "id": "9g0d", "nombre": "This Week" })
db.estadosUnidos.insertOne({ "id": "9g0a", "nombre": "Visiting In Yuma" })
db.estadosUnidos.insertOne({ "id": "9g12", "nombre": "Yuma Sun       " })
db.estadosUnidos.insertOne({ "id": "9wtt", "nombre": "Yuma Visitors Map" })
db.estadosUnidos.insertOne({ "id": "9ht2", "nombre": "iD magazine" })
db.estadosUnidos.insertOne({ "id": "9fgj", "nombre": "iPhone Life Magazine" })
db.estadosUnidos.insertOne({ "id": "9551", "nombre": "net magazine" })
