db.alemania.insertOne({ "id":"9vm8", "name": "Raw mit Photoshop" })
db.alemania.insertOne({ "id":"3658", "name": "20 Private Wohntraeume" })
db.alemania.insertOne({ "id":"34b9", "name": "AUTO ZEITUNG" })
db.alemania.insertOne({ "id":"34be", "name": "AUTO ZEITUNG Classic Cars" })
db.alemania.insertOne({ "id":"3624", "name": "Aalener Nachrichten" })
db.alemania.insertOne({ "id":"3190", "name": "Abendzeitung München" })
db.alemania.insertOne({ "id":"34rq", "name": "Adesso" })
db.alemania.insertOne({ "id":"369j", "name": "Aichacher Nachrichten" })
db.alemania.insertOne({ "id":"9huy", "name": "Alb Bote (Münsingen)" })
db.alemania.insertOne({ "id":"36g0", "name": "All About Italy (Germany)" })
db.alemania.insertOne({ "id":"34gl", "name": "Aller-Zeitung" })
db.alemania.insertOne({ "id":"34hu", "name": "Allgäuer Anzeigeblatt" })
db.alemania.insertOne({ "id":"34ht", "name": "Allgäuer Zeitung (Füssener Blatt)" })
db.alemania.insertOne({ "id":"34hw", "name": "Allgäuer Zeitung (Kaufbeurer Tagblatt)" })
db.alemania.insertOne({ "id":"34hv", "name": "Allgäuer Zeitung (Kempter Tagblatt)" })
db.alemania.insertOne({ "id":"34hy", "name": "Allgäuer Zeitung (Marktoberdorfer Landbote)" })
db.alemania.insertOne({ "id":"34b8", "name": "Astrowoche" })
db.alemania.insertOne({ "id":"34f4", "name": "Audio" })
db.alemania.insertOne({ "id":"369g", "name": "Augsburger Allgemeine (Ausgabe Stadt)" })
db.alemania.insertOne({ "id":"369l", "name": "Augsburger Allgemeine (Land Nord)" })
db.alemania.insertOne({ "id":"369m", "name": "Augsburger Allgemeine (Land West)" })
db.alemania.insertOne({ "id":"34lf", "name": "Auszeit" })
db.alemania.insertOne({ "id":"9xv2", "name": "Autocad and Inventor Magazin" })
db.alemania.insertOne({ "id":"3659", "name": "Bad &amp; Kueche" })
db.alemania.insertOne({ "id":"9xv3", "name": "Bauen Aktuell" })
db.alemania.insertOne({ "id":"9vjb", "name": "Beat" })
db.alemania.insertOne({ "id":"34ba", "name": "Bella" })
db.alemania.insertOne({ "id":"9wt3", "name": "Bergische Morgenpost Wermelskirchen/Hückeswagen/Radevormwald" })
db.alemania.insertOne({ "id":"36b2", "name": "Bersenbrucker Kreisblatt" })
db.alemania.insertOne({ "id":"9huz", "name": "Bietigheimer Zeitung" })
db.alemania.insertOne({ "id":"34l7", "name": "Blu-ray Magazin" })
db.alemania.insertOne({ "id":"36b1", "name": "Bramscher Nachrichten" })
db.alemania.insertOne({ "id":"34bb", "name": "Bravo" })
db.alemania.insertOne({ "id":"34bc", "name": "Bravo Girl!" })
db.alemania.insertOne({ "id":"34hs", "name": "Buchloer Zeitung" })
db.alemania.insertOne({ "id":"36f8", "name": "Bunte" })
db.alemania.insertOne({ "id":"34rr", "name": "Business Spotlight" })
db.alemania.insertOne({ "id":"3396", "name": "Business Traveller (Germany)" })
db.alemania.insertOne({ "id":"9vjd", "name": "Bücher Magazin" })
db.alemania.insertOne({ "id":"9vjf", "name": "CanonFoto" })
db.alemania.insertOne({ "id":"3360", "name": "Chemnitzer Morgenpost" })
db.alemania.insertOne({ "id":"8398", "name": "China Daily European Weekly" })
db.alemania.insertOne({ "id":"9gau", "name": "Chronos" })
db.alemania.insertOne({ "id":"34f5", "name": "ColorFoto" })
db.alemania.insertOne({ "id":"5669", "name": "Computerwoche" })
db.alemania.insertOne({ "id":"34bg", "name": "Cosmopolitan (Germany)" })
db.alemania.insertOne({ "id":"34rf", "name": "Country Homes (Germany)" })
db.alemania.insertOne({ "id":"9vue", "name": "Crucero - Das Kreuzfahrtmagazin" })
db.alemania.insertOne({ "id":"34c1", "name": "DAS NEUE BLATT" })
db.alemania.insertOne({ "id":"36f9", "name": "DONNA" })
db.alemania.insertOne({ "id":"34bh", "name": "Das Neue" })
db.alemania.insertOne({ "id":"36b8", "name": "Delmenhorster Kreisblatt" })
db.alemania.insertOne({ "id":"34l8", "name": "Der Fachhandler" })
db.alemania.insertOne({ "id":"3035", "name": "Der Tagesspiegel" })
db.alemania.insertOne({ "id":"34hz", "name": "Der Westallgäuer" })
db.alemania.insertOne({ "id":"34rs", "name": "Deutsch Perfekt" })
db.alemania.insertOne({ "id":"3662", "name": "Die Schoensten Landhaeuser" })
db.alemania.insertOne({ "id":"3663", "name": "Die Schoensten Wohntraeume" })
db.alemania.insertOne({ "id":"9xv4", "name": "Digital Business Cloud" })
db.alemania.insertOne({ "id":"9xv5", "name": "Digital Engineering Magazin" })
db.alemania.insertOne({ "id":"34l9", "name": "Digital Fernsehen" })
db.alemania.insertOne({ "id":"9xv6", "name": "Digital Manufacturing" })
db.alemania.insertOne({ "id":"34la", "name": "Digital Tested" })
db.alemania.insertOne({ "id":"34d2", "name": "DigitalPHOTO (Germany)" })
db.alemania.insertOne({ "id":"369u", "name": "Donau Zeitung" })
db.alemania.insertOne({ "id":"369q", "name": "Donauwoerther Zeitung" })
db.alemania.insertOne({ "id":"3359", "name": "Dresdner Morgenpost" })
db.alemania.insertOne({ "id":"34gm", "name": "Dresdner Neueste Nachrichten" })
db.alemania.insertOne({ "id":"9xv7", "name": "E-Commerce Magazin" })
db.alemania.insertOne({ "id":"9klh", "name": "ERFOLG Magazin" })
db.alemania.insertOne({ "id":"34rt", "name": "Ecos" })
db.alemania.insertOne({ "id":"34rw", "name": "Ecoute" })
db.alemania.insertOne({ "id":"34gn", "name": "Eichsfelder Tageblatt" })
db.alemania.insertOne({ "id":"36b7", "name": "Ems-Zeitung" })
db.alemania.insertOne({ "id":"9gga", "name": "Feuerwehr-Magazin" })
db.alemania.insertOne({ "id":"9hzd", "name": "Food and Travel (Germany)" })
db.alemania.insertOne({ "id":"9vjn", "name": "FotoBIBEL" })
db.alemania.insertOne({ "id":"9vjp", "name": "FotoEASY" })
db.alemania.insertOne({ "id":"36fb", "name": "Freundin" })
db.alemania.insertOne({ "id":"369k", "name": "Friedberger Allgemeine" })
db.alemania.insertOne({ "id":"3664", "name": "Garden Style" })
db.alemania.insertOne({ "id":"34uk", "name": "Garten Welt" })
db.alemania.insertOne({ "id":"9hv1", "name": "Geislinger Zeitung" })
db.alemania.insertOne({ "id":"9gaw", "name": "Gitarre &amp; Bass" })
db.alemania.insertOne({ "id":"34bk", "name": "Good Health (Germany)" })
db.alemania.insertOne({ "id":"3642", "name": "Graenzbote" })
db.alemania.insertOne({ "id":"369r", "name": "Guenzburger Zeitung" })
db.alemania.insertOne({ "id":"34gp", "name": "Göttinger Tageblatt" })
db.alemania.insertOne({ "id":"34lc", "name": "HD TV" })
db.alemania.insertOne({ "id":"9huw", "name": "Haller Tagblatt" })
db.alemania.insertOne({ "id":"3021", "name": "Hamburger Morgenpost" })
db.alemania.insertOne({ "id":"ta37", "name": "Handelsblatt Global Edition Magazine" })
db.alemania.insertOne({ "id":"3155", "name": "Hannoversche Allgemeine" })
db.alemania.insertOne({ "id":"34bl", "name": "Happinez" })
db.alemania.insertOne({ "id":"34lb", "name": "Haus &amp; Garten Test" })
db.alemania.insertOne({ "id":"9hv2", "name": "Heidenheimer Neue Presse" })
db.alemania.insertOne({ "id":"9hv3", "name": "Heidenheimer Zeitung" })
db.alemania.insertOne({ "id":"3629", "name": "Heuberger Bote" })
db.alemania.insertOne({ "id":"9hux", "name": "Hohenloher Tagblatt" })
db.alemania.insertOne({ "id":"9hyi", "name": "Hohenzollerische Zeitung" })
db.alemania.insertOne({ "id":"3665", "name": "Holiday &amp; Lifestyle" })
db.alemania.insertOne({ "id":"34r7", "name": "Homes &amp; Gardens (Germany)" })
db.alemania.insertOne({ "id":"34rd", "name": "Ich Bin" })
db.alemania.insertOne({ "id":"369t", "name": "Illertisser Zeitung" })
db.alemania.insertOne({ "id":"34gy", "name": "In München" })
db.alemania.insertOne({ "id":"3627", "name": "Ipf- und Jagst-Zeitung" })
db.alemania.insertOne({ "id":"34bn", "name": "JOY (Germany)" })
db.alemania.insertOne({ "id":"ee18", "name": "Karibik" })
db.alemania.insertOne({ "id":"34bp", "name": "Kochen &amp; Genießen" })
db.alemania.insertOne({ "id":"369p", "name": "Koenigsbrunner Zeitung" })
db.alemania.insertOne({ "id":"3602", "name": "Kruschelpost" })
db.alemania.insertOne({ "id":"9k45", "name": "L'Officiel Germany" })
db.alemania.insertOne({ "id":"9k46", "name": "L'Officiel Hommes Germany" })
db.alemania.insertOne({ "id":"9hm6", "name": "LUXE City Guides - Berlin" })
db.alemania.insertOne({ "id":"9vjs", "name": "LandGenuss" })
db.alemania.insertOne({ "id":"3667", "name": "Landhaus Living" })
db.alemania.insertOne({ "id":"3668", "name": "Landleben" })
db.alemania.insertOne({ "id":"369w", "name": "Landsberger Tagblatt" })
db.alemania.insertOne({ "id":"34br", "name": "Laura" })
db.alemania.insertOne({ "id":"34bt", "name": "Laura WOHNEN Kreativ" })
db.alemania.insertOne({ "id":"36g4", "name": "Lecker" })
db.alemania.insertOne({ "id":"34gr", "name": "Leipziger Volkszeitung" })
db.alemania.insertOne({ "id":"3633", "name": "Lindauer Zeitung" })
db.alemania.insertOne({ "id":"36b5", "name": "Lingener Tagespost" })
db.alemania.insertOne({ "id":"34ry", "name": "Lübecker Nachrichten" })
db.alemania.insertOne({ "id":"34d1", "name": "Mac Life" })
db.alemania.insertOne({ "id":"9vjv", "name": "Mac Life Wissen" })
db.alemania.insertOne({ "id":"9vjt", "name": "MacBIBEL" })
db.alemania.insertOne({ "id":"34p3", "name": "Mallorca geht aus!" })
db.alemania.insertOne({ "id":"34uh", "name": "Mate (Germany)" })
db.alemania.insertOne({ "id":"9vju", "name": "Mein LandRezept" })
db.alemania.insertOne({ "id":"3670", "name": "Mein Landgarten" })
db.alemania.insertOne({ "id":"34bs", "name": "Mein Lieblingsrezept" })
db.alemania.insertOne({ "id":"9vjx", "name": "Mein ZauberTopf" })
db.alemania.insertOne({ "id":"34bu", "name": "Meins" })
db.alemania.insertOne({ "id":"9vm9", "name": "Meisterkurs SchwarzWeiß" })
db.alemania.insertOne({ "id":"36b4", "name": "Meller Kreisblatt" })
db.alemania.insertOne({ "id":"34hx", "name": "Memminger Zeitung" })
db.alemania.insertOne({ "id":"36b6", "name": "Meppener Tagespost" })
db.alemania.insertOne({ "id":"369x", "name": "Mindelheimer Zeitung" })
db.alemania.insertOne({ "id":"369v", "name": "Mittelschwaebische Nachrichten" })
db.alemania.insertOne({ "id":"3363", "name": "Morgenpost am Sonntag (Chemnitzer)" })
db.alemania.insertOne({ "id":"3362", "name": "Morgenpost am Sonntag (Dresdner)" })
db.alemania.insertOne({ "id":"34gs", "name": "Märkische Allgemeine" })
db.alemania.insertOne({ "id":"9hrz", "name": "Märkische Oderzeitung Angerm‎ünde" })
db.alemania.insertOne({ "id":"9hsg", "name": "Märkische Oderzeitung Bad Freienwalde" })
db.alemania.insertOne({ "id":"9hsa", "name": "Märkische Oderzeitung Beeskow" })
db.alemania.insertOne({ "id":"9hsb", "name": "Märkische Oderzeitung Bernau" })
db.alemania.insertOne({ "id":"9hsc", "name": "Märkische Oderzeitung Eberswalde" })
db.alemania.insertOne({ "id":"9hsd", "name": "Märkische Oderzeitung Eisenhüttenstadt" })
db.alemania.insertOne({ "id":"9hse", "name": "Märkische Oderzeitung Erkner" })
db.alemania.insertOne({ "id":"9hsf", "name": "Märkische Oderzeitung Frankfurt" })
db.alemania.insertOne({ "id":"9hsh", "name": "Märkische Oderzeitung Fürstenwalde" })
db.alemania.insertOne({ "id":"9hsk", "name": "Märkische Oderzeitung Schwedt" })
db.alemania.insertOne({ "id":"9hsi", "name": "Märkische Oderzeitung Seelow" })
db.alemania.insertOne({ "id":"9hsj", "name": "Märkische Oderzeitung Strausberg" })
db.alemania.insertOne({ "id":"9hsl", "name": "Märkischer Zeitungsverlag Oranienburger Generalanzeiger" })
db.alemania.insertOne({ "id":"9hv5", "name": "NWZ  (Göppinger Kreisnachrichten)" })
db.alemania.insertOne({ "id":"9vk1", "name": "NaturApotheke" })
db.alemania.insertOne({ "id":"369s", "name": "Neu-Ulmer Zeitung" })
db.alemania.insertOne({ "id":"369y", "name": "Neuburger Rundschau" })
db.alemania.insertOne({ "id":"36c4", "name": "Neue Osnabrucker Zeitung - Bad Laer, Bad Rothenfelde, Dissen, G" })
db.alemania.insertOne({ "id":"36c1", "name": "Neue Osnabrucker Zeitung - Bissendorf, Belm" })
db.alemania.insertOne({ "id":"36c3", "name": "Neue Osnabrucker Zeitung - Georgsmarienhutte, Bad Iburg, Hilter" })
db.alemania.insertOne({ "id":"36c2", "name": "Neue Osnabrucker Zeitung - Hagen, Hasbergen" })
db.alemania.insertOne({ "id":"36c5", "name": "Neue Osnabrucker Zeitung - Lotte, Westerkappeln, Mettingen, Tecklenburg" })
db.alemania.insertOne({ "id":"36a9", "name": "Neue Osnabrucker Zeitung - Stadt Osnabruck" })
db.alemania.insertOne({ "id":"36b9", "name": "Neue Osnabrucker Zeitung - Wallenhorst" })
db.alemania.insertOne({ "id":"34c2", "name": "Neue Post" })
db.alemania.insertOne({ "id":"3148", "name": "Neue Presse" })
db.alemania.insertOne({ "id":"34hl", "name": "Neue Westfälische - Bad Oeynhausener Kurier" })
db.alemania.insertOne({ "id":"34hd", "name": "Neue Westfälische - Bielefelder Tageblatt - Bielefeld Dornberg - Werther" })
db.alemania.insertOne({ "id":"34ha", "name": "Neue Westfälische - Bielefelder Tageblatt - Bielefeld Ost" })
db.alemania.insertOne({ "id":"34hb", "name": "Neue Westfälische - Bielefelder Tageblatt - Bielefeld Süd" })
db.alemania.insertOne({ "id":"34gz", "name": "Neue Westfälische - Bielefelder Tageblatt - Bielefeld West" })
db.alemania.insertOne({ "id":"34hc", "name": "Neue Westfälische - Bielefelder Tageblatt - Bielefeld mit Oerlinghausen" })
db.alemania.insertOne({ "id":"34hk", "name": "Neue Westfälische - Bünder Tageblatt" })
db.alemania.insertOne({ "id":"34hf", "name": "Neue Westfälische - Gütersloher Zeitung" })
db.alemania.insertOne({ "id":"34hh", "name": "Neue Westfälische - Herforder Kreisanzeiger" })
db.alemania.insertOne({ "id":"34hq", "name": "Neue Westfälische - Höxtersche Kreiszeitung" })
db.alemania.insertOne({ "id":"34hr", "name": "Neue Westfälische - Kreiszeitung für Warburg" })
db.alemania.insertOne({ "id":"34hm", "name": "Neue Westfälische - Löhner Nachrichten" })
db.alemania.insertOne({ "id":"34hp", "name": "Neue Westfälische - Paderborner Kreiszeitung" })
db.alemania.insertOne({ "id":"34hj", "name": "Neue Westfälische - Tageblatt für Enger und Spenge" })
db.alemania.insertOne({ "id":"34he", "name": "Neue Westfälische - Tageblatt für Schloß Holte-Stukenbrock" })
db.alemania.insertOne({ "id":"34hg", "name": "Neue Westfälische - Verler Tageblatt" })
db.alemania.insertOne({ "id":"34hn", "name": "Neue Westfälische - Zeitung für das Lübbecker Land" })
db.alemania.insertOne({ "id":"3605", "name": "Neues Deutschland" })
db.alemania.insertOne({ "id":"9wt1", "name": "Neuss Grevenbroicher Zeitung Grevenbroich/Dormagen" })
db.alemania.insertOne({ "id":"3180", "name": "Neuss-Grevenbroicher Zeitung (Neuss)" })
db.alemania.insertOne({ "id":"9vk2", "name": "NikonBIBEL" })
db.alemania.insertOne({ "id":"9huj", "name": "Nordwest-Zeitung" })
db.alemania.insertOne({ "id":"34rz", "name": "Ostsee Zeitung" })
db.alemania.insertOne({ "id":"9gg5", "name": "Ostthüringer Zeitung (Bad Lobenstein)" })
db.alemania.insertOne({ "id":"9gg6", "name": "Ostthüringer Zeitung (Eisenberg)" })
db.alemania.insertOne({ "id":"9gfm", "name": "Ostthüringer Zeitung (Gera)" })
db.alemania.insertOne({ "id":"9gg7", "name": "Ostthüringer Zeitung (Greiz)" })
db.alemania.insertOne({ "id":"9gg8", "name": "Ostthüringer Zeitung (Jena)" })
db.alemania.insertOne({ "id":"9gg9", "name": "Ostthüringer Zeitung (Pößneck)" })
db.alemania.insertOne({ "id":"9gkj", "name": "Ostthüringer Zeitung (Rudolstadt)" })
db.alemania.insertOne({ "id":"9gkk", "name": "Ostthüringer Zeitung (Saalfeld)" })
db.alemania.insertOne({ "id":"9gkl", "name": "Ostthüringer Zeitung (Schleiz)" })
db.alemania.insertOne({ "id":"9gkm", "name": "Ostthüringer Zeitung (Schmölln)" })
db.alemania.insertOne({ "id":"9gkn", "name": "Ostthüringer Zeitung (Stadtroda)" })
db.alemania.insertOne({ "id":"9gkp", "name": "Ostthüringer Zeitung (Zeulenroda-Triebes)" })
db.alemania.insertOne({ "id":"9vk3", "name": "Outdoor Fotografie" })
db.alemania.insertOne({ "id":"9gat", "name": "PAGE" })
db.alemania.insertOne({ "id":"34fa", "name": "PC Magazin" })
db.alemania.insertOne({ "id":"5668", "name": "PC-WELT" })
db.alemania.insertOne({ "id":"34fb", "name": "PCgo" })
db.alemania.insertOne({ "id":"34gu", "name": "Peiner Allgemeine Zeitung" })
db.alemania.insertOne({ "id":"9vm7", "name": "Photoshop Handbuch" })
db.alemania.insertOne({ "id":"9vm6", "name": "Photoshop Lightroom" })
db.alemania.insertOne({ "id":"9vk4", "name": "PhotoshopBIBEL" })
db.alemania.insertOne({ "id":"3946", "name": "ProZukunft" })
db.alemania.insertOne({ "id":"9gay", "name": "Production Partner" })
db.alemania.insertOne({ "id":"34c3", "name": "REZEPTE pur" })
db.alemania.insertOne({ "id":"9hv6", "name": "Reutlinger Nachrichten&nbsp;" })
db.alemania.insertOne({ "id":"3012", "name": "Rheinische Post" })
db.alemania.insertOne({ "id":"9wsw", "name": "Rheinische Post - Geldern an Kevelaer" })
db.alemania.insertOne({ "id":"9wsv", "name": "Rheinische Post - Kleve, Goch and Emmerich" })
db.alemania.insertOne({ "id":"9wsy", "name": "Rheinische Post - Mönchengladbach and Korschenbroich" })
db.alemania.insertOne({ "id":"9wsx", "name": "Rheinische Post - Opladen/Langenfeld" })
db.alemania.insertOne({ "id":"9wsu", "name": "Rheinische Post - Wesel/Dinslaken" })
db.alemania.insertOne({ "id":"9wsz", "name": "Rheinische Post - Xanten and Moers" })
db.alemania.insertOne({ "id":"3151", "name": "Rheinische Post Duesseldorf Meerbusch" })
db.alemania.insertOne({ "id":"3161", "name": "Rheinische Post Duisburg" })
db.alemania.insertOne({ "id":"3164", "name": "Rheinische Post Erkelenz" })
db.alemania.insertOne({ "id":"3149", "name": "Rheinische Post Hilden" })
db.alemania.insertOne({ "id":"3171", "name": "Rheinische Post Krefeld Kempen" })
db.alemania.insertOne({ "id":"3152", "name": "Rheinische Post Mettmann " })
db.alemania.insertOne({ "id":"3156", "name": "Rheinische Post Ratingen" })
db.alemania.insertOne({ "id":"3183", "name": "Rheinische Post Viersen" })
db.alemania.insertOne({ "id":"9wst", "name": "Rheinische Post – Düsseldorf Mitte/West/Ost/Nord/Süd" })
db.alemania.insertOne({ "id":"369z", "name": "Rieser Nachrichten" })
db.alemania.insertOne({ "id":"9hsp", "name": "Rundschau für den Schwäbischen Wald – Der Kocherbote" })
db.alemania.insertOne({ "id":"34c4", "name": "SHAPE (Germany)" })
db.alemania.insertOne({ "id":"3205", "name": "Saarbruecker Zeitung" })
db.alemania.insertOne({ "id":"9kli", "name": "Sachwert Magazin" })
db.alemania.insertOne({ "id":"34ld", "name": "Satellit Empfang + Technik" })
db.alemania.insertOne({ "id":"369n", "name": "Schwabmuenchner Allgemeine" })
db.alemania.insertOne({ "id":"3630", "name": "Schwaebische Zeitung (Alb-Donau)" })
db.alemania.insertOne({ "id":"3638", "name": "Schwaebische Zeitung (Bad Saulgau)" })
db.alemania.insertOne({ "id":"3643", "name": "Schwaebische Zeitung (Bad Waldsee / Aulendorf)" })
db.alemania.insertOne({ "id":"3625", "name": "Schwaebische Zeitung (Biberach)" })
db.alemania.insertOne({ "id":"3626", "name": "Schwaebische Zeitung (Ehingen)" })
db.alemania.insertOne({ "id":"3628", "name": "Schwaebische Zeitung (Friedrichshafen)" })
db.alemania.insertOne({ "id":"3632", "name": "Schwaebische Zeitung (Laupheim)" })
db.alemania.insertOne({ "id":"3631", "name": "Schwaebische Zeitung (Leutkirch / Isny / Bad Wurzach)" })
db.alemania.insertOne({ "id":"3613", "name": "Schwaebische Zeitung (Ravensburg / Weingarten)" })
db.alemania.insertOne({ "id":"3637", "name": "Schwaebische Zeitung (Riedlingen)" })
db.alemania.insertOne({ "id":"3639", "name": "Schwaebische Zeitung (Sigmaringen)" })
db.alemania.insertOne({ "id":"3640", "name": "Schwaebische Zeitung (Tettnang)" })
db.alemania.insertOne({ "id":"3644", "name": "Schwaebische Zeitung (Wangen)" })
db.alemania.insertOne({ "id":"9vk5", "name": "So is(s)t Italien" })
db.alemania.insertOne({ "id":"9vnb", "name": "So is(s)t Italien Special Edition" })
db.alemania.insertOne({ "id":"9wt4", "name": "Solinger Bergische Morgenpost/Remscheid" })
db.alemania.insertOne({ "id":"9vk6", "name": "SonyBIBEL" })
db.alemania.insertOne({ "id":"34uj", "name": "Spartacus Traveler" })
db.alemania.insertOne({ "id":"34ru", "name": "Spotlight" })
db.alemania.insertOne({ "id":"34fd", "name": "Stereoplay" })
db.alemania.insertOne({ "id":"9vk7", "name": "Sweet Paul" })
db.alemania.insertOne({ "id":"9hv4", "name": "Südwest Presse (Metzinger Uracher Volksblatt / Der Ermstalbote)" })
db.alemania.insertOne({ "id":"9hv7", "name": "Südwest Presse (Ulm)" })
db.alemania.insertOne({ "id":"9vrg", "name": "Tendency" })
db.alemania.insertOne({ "id":"34qe", "name": "Test Journal" })
db.alemania.insertOne({ "id":"34le", "name": "Testjahrbuch" })
db.alemania.insertOne({ "id":"9gfp", "name": "Thüringer Allgemeine (Apolda)" })
db.alemania.insertOne({ "id":"9gfq", "name": "Thüringer Allgemeine (Arnstadt)" })
db.alemania.insertOne({ "id":"9gfr", "name": "Thüringer Allgemeine (Artern)" })
db.alemania.insertOne({ "id":"9gfs", "name": "Thüringer Allgemeine (Bad Langensalza)" })
db.alemania.insertOne({ "id":"9gft", "name": "Thüringer Allgemeine (Eichsfeld)" })
db.alemania.insertOne({ "id":"9gfu", "name": "Thüringer Allgemeine (Eisenach)" })
db.alemania.insertOne({ "id":"9gaz", "name": "Thüringer Allgemeine (Erfurt)" })
db.alemania.insertOne({ "id":"9gg3", "name": "Thüringer Allgemeine (Erfurt-Land)" })
db.alemania.insertOne({ "id":"9gfv", "name": "Thüringer Allgemeine (Gotha)" })
db.alemania.insertOne({ "id":"9gfw", "name": "Thüringer Allgemeine (Ilmenau)" })
db.alemania.insertOne({ "id":"9gfx", "name": "Thüringer Allgemeine (Mühlhausen)" })
db.alemania.insertOne({ "id":"9gfy", "name": "Thüringer Allgemeine (Nordhausen)" })
db.alemania.insertOne({ "id":"9gfz", "name": "Thüringer Allgemeine (Sondershausen)" })
db.alemania.insertOne({ "id":"9gg1", "name": "Thüringer Allgemeine (Sömmerda)" })
db.alemania.insertOne({ "id":"9gg2", "name": "Thüringer Allgemeine (Weimar)" })
db.alemania.insertOne({ "id":"9gkq", "name": "Thüringische Landeszeitung (Eichsfeld)" })
db.alemania.insertOne({ "id":"9gkr", "name": "Thüringische Landeszeitung (Eisenach)" })
db.alemania.insertOne({ "id":"9gks", "name": "Thüringische Landeszeitung (Erfurt)" })
db.alemania.insertOne({ "id":"9gkt", "name": "Thüringische Landeszeitung (Gera)" })
db.alemania.insertOne({ "id":"9gku", "name": "Thüringische Landeszeitung (Gotha)" })
db.alemania.insertOne({ "id":"9gkv", "name": "Thüringische Landeszeitung (Jena)" })
db.alemania.insertOne({ "id":"9gkw", "name": "Thüringische Landeszeitung (Unstrut-Hainich-Kreis)" })
db.alemania.insertOne({ "id":"9gfn", "name": "Thüringische Landeszeitung (Weimar)" })
db.alemania.insertOne({ "id":"34c8", "name": "Tina Koch &amp; Backideen" })
db.alemania.insertOne({ "id":"3671", "name": "Traumgaerten" })
db.alemania.insertOne({ "id":"3672", "name": "Traumwohnen" })
db.alemania.insertOne({ "id":"3641", "name": "Trossinger Zeitung" })
db.alemania.insertOne({ "id":"9gav", "name": "Uhren-Magazin" })
db.alemania.insertOne({ "id":"9i18", "name": "VDI Nachrichten" })
db.alemania.insertOne({ "id":"34ca", "name": "WOHNIDEE" })
db.alemania.insertOne({ "id":"368a", "name": "Wertinger Zeitung" })
db.alemania.insertOne({ "id":"9d59", "name": "Where Berlin" })
db.alemania.insertOne({ "id":"36b3", "name": "Wittlager Kreisblatt" })
db.alemania.insertOne({ "id":"34gv", "name": "Wolfsburger Allgemeine" })
db.alemania.insertOne({ "id":"34f6", "name": "connect" })
db.alemania.insertOne({ "id":"9vjq", "name": "iPhone &amp; iPad Life" })
db.alemania.insertOne({ "id":"9vjr", "name": "iPhoneBIBEL" })
db.alemania.insertOne({ "id":"9vnc", "name": "mein ZauberTopf Special Edition" })
db.alemania.insertOne({ "id":"9kvq", "name": "reisen EXCLUSIV" })
db.alemania.insertOne({ "id":"3495", "name": "selbst ist der Mann" })
db.alemania.insertOne({ "id":"34c6", "name": "tina" })
db.alemania.insertOne({ "id":"34fe", "name": "video" })
